KhronosGroup/Vulkan-Tools

BUILD.md
Remove outdated link.
Change-Id: I8764e470fe11646fc13cc62e73761c09e2779f6a
=> docs: Update build doc

.appveyor.yml, .travis.yml
Adapt to Vulkan-Loader getting rid of Vulkan-Headers submodule.
Get and build Vulkan-Headers and fix Vulkan-Loader build to use it.
=> build: Fix CI for updated Vulkan-Loader

BUILD.md, CMakeLists.txt, cube/CMakeLists.txt, vulkaninfo/CMakeLists.txt
=> repo: Remove interim REPO_ROOT CMake code

vulkaninfo/vulkaninfo.c
Added output for VkPhysicalDeviceMaintenance3Properties
struct info.
=> vulkaninfo: Add VK_KHR_maintenance3 support

vulkaninfo/vulkaninfo.c
Prior to this change, html output was not nested properly for systems with multiple gpus.
=> vulkaninfo: Fix html output for multiple gpus

BUILD.md, scripts/known_good.json, scripts/update_deps.py
Change-Id: I05fe4162054fc90edd1642ab08644f6ee7950548
=> build: Add known-good support

scripts/update_deps.py
Makes `update_deps.py` consistent between repos.
=> build: Unify `update_deps.py` between repos

icd/linux/VkICD_mock_icd.json, icd/macos/VkICD_mock_icd.json, icd/windows/VkICD_mock_icd.json, scripts/known_good.json
Change-Id: I1fa27ee2564cf676418be543d6e2e2cb7f1cd906
=> repo: Update known-good for Vulkan-Headers

vulkaninfo/vulkaninfo.c
Added output for VkPhysicalDevice8bitStorageFeaturesKHR
struct info to vulkaninfo.
=> vulkaninfo: Add VK_KHR_8bit_storage support

.cmake-format.py, BUILD.md, CMakeLists.txt, cmake/FindVulkan.cmake, cube/CMakeLists.txt, cube/macOS/cube/cube.cmake, cube/macOS/cubepp/cubepp.cmake, icd/CMakeLists.txt, vulkaninfo/CMakeLists.txt, vulkaninfo/macOS/vulkaninfo.cmake
This is the first PR cleaning up CMake files in Khronos repos. It consists primarily of cleanup, dead code/variable removal, and simplification.
This PR (in its current form of many separate commits) meant to make it easier to review; it will be squashed to a single commit before pushing to VT master.
=> CMake cleanup, part 1

cube/cube.c, cube/cube.cpp
Addresses #66 - Can't assume linear image is available.
=> cube: Use staging buffer instead of staging image

scripts/known_good.json, scripts/update_deps.py
Syncing update_deps.py with changes
made in Vulkan-ValidationLayer PR 285.
=> build: Sync update_deps.py

scripts/known_good.json
Updated MoltenVK commit ID in known_good.json to
e651841e67e6faddaaa8e5848d248c4b1b7ad3cf.
=> build: Update MoltenVK known_good.json

scripts/known_good.json
Updated:
- `scripts/known_good.json`
=> layers: Bump glslang known-good

scripts/known_good.json
Updated:
- `scripts/known_good.json`
=> build: Update known-good for 1.1.91 header

vulkaninfo/vulkaninfo.c
=> vulkaninfo: Set missing sType and pNext in surf_formats2 array.

scripts/mock_icd_generator.py
Track the buffer create info from CreateBuffer so that
GetBufferMemoryRequirements can return an actual size
instead of a hard-coded guess.
Needed to survive VLT setup during GPU validation testing.
=> icd: Return better size in GetBufferMemoryReq

vulkaninfo/vulkaninfo.c
=> vulkaninfo: Properly check vk commands error codes

vulkaninfo/vulkaninfo.c
=> vulkaninfo: Make queue families report present support

scripts/known_good.json
Updated the commit ID for MoltenVK in
known-good.json after SDK release.
=> macos: Update known-good.json

vulkaninfo/vulkaninfo.c
- localize `VkPhysicalDeviceSurfaceInfo2KHR` (and remove from instance creation)
- <s>Remove debug callback. We are not even enabling any layers...</s>
- Enable all supported instance extensions. Close #100.
- Prettify instance command loader
- other esthetics
=> vulkaninfo: Rewrite instance creation

vulkaninfo/vulkaninfo.c
Adding the VK_MEMORY_PROPERTY_PROTECTED_BIT in the printing.
Could you please kindly review this change?
Thanks in advance.
=> vulkaninfo: print VK_MEMORY_PROPERTY_PROTECTED_BIT

cube/cube.c, cube/cube.cpp
=> vkcube: Implement key events in Windows

vulkaninfo/vulkaninfo.c
I know that there is no planned work for vulkaninfo for Android.
But someone will use the vulkaninfo crossing all the platforms
including Android.
This change fixed the compiling error on Android platform.
=> Fix the build error on Android

vulkaninfo/vulkaninfo.md
=> docs: Add vulkaninfo.md

vulkaninfo/vulkaninfo.c
Added listing for all present extensions and
listing for present support for each extension on
GPU queue families.
Fixed validation error in function AppGroupDump.
=> vulkaninfo: Fix Leak with Multiple Surfaces

vulkaninfo/vulkaninfo.c
=> vulkaninfo: Remove invalid json for present_support 

.appveyor.yml, .travis.yml, BUILD.md
Updated suggested CMake version for platforms in
BUILD.md.
Added CMake version output on Travis and AppVeyor.
=> build: Update CMake version

GOVERNANCE.md
Updated GOVERNANCE.md to better reflect the
KhronosGroup/Vulkan-Tools repo.
=> docs: Update GOVERNANCE

vulkaninfo/vulkaninfo.c
Updated vulkaninfo HTML output to fix errors and
warnings output by https://validator.w3.org.
Fixes issue #163
=>  vulkaninfo: Fix HTML output warnings and errors 

vulkaninfo/vulkaninfo.c
From the following extensions:
VK_EXT_memory_priority
VK_EXT_memory_budget
VK_EXT_buffer_device_address
VK_KHR_depth_stencil_resolve
Added output for the following structures:
VkPhysicalDeviceMemoryPriorityFeaturesEXT
VkPhysicalDeviceMemoryBudgetPropertiesEXT
VkPhysicalDeviceBufferAddressFeaturesEXT
VkPhysicalDeviceDepthStencilResolvePropertiesKHR
=> vulkaninfo: Add extension output

cube/cube.c, cube/cube.cpp, vulkaninfo/vulkaninfo.c
Our internal coverity scan ran over this, and I thought I'd send some of the trivial fixes.
=> Coverity fixes

scripts/known_good.json
Updated the MoltenVK version in known_good.json to
"v1.0.34"
=> known_good: Update MoltenVK known_good version ID

cube/cube.c, cube/cube.cpp
=> cube: Add usage message on Windows

scripts/known_good.json
Updated MoltenVK version in known_good.json
from 1.0.34v -> 1.0.35v
=> build: Update MoltenVK in known_good.json

BUILD.md
[ci skip]
Same change as KhronosGroup/Vulkan-ValidationLayers#955
=> docs: Improve instructions for using update_deps.

.appveyor.yml, .travis.yml, BUILD.gn, BUILD.md, CMakeLists.txt, CONTRIBUTING.md, icd/CMakeLists.txt, icd/generated/.clang-format, icd/generated/mock_icd.cpp, icd/generated/mock_icd.h, icd/generated/vk_typemap_helper.h, scripts/common_codegen.py, scripts/generate_source.py, scripts/kvt_genvk.py, scripts/mock_icd_generator.py
Fixes #224 
This should all feel very familiar...
=> Offline source code generation

scripts/known_good.json
Updated MoltenVK version in known-good.json from
v1.0.35 -> v1.0.36
=> build: Update MoltenVK version in known-good.json

vulkaninfo/vulkaninfo.c
Implements the extension in vulkaninfo
Change-Id: I67ec93c678f0537ea00222bdd35e1e18b28c85d1
=> vulkaninfo: VK_KHR_uniform_buffer_standard_layout

vulkaninfo/vulkaninfo.c
Adds support for the extension.
Change-Id: Ifc18acbdeae3b1b5b568e9a3ddaffb444d14ef86
=> vulkaninfo: VK_EXT_fragment_shader_interlock

vulkaninfo/vulkaninfo.c
Change-Id: I5188ffd477d16a3af8d48c69dc411feee76b1f7f
=> vulkaninfo: Support for ShaderDemoteToHelperInvocationExt

vulkaninfo/vulkaninfo.c
Change-Id: I99965dabaf7307e52c56f779d79f259fc379c7da
=> vulkaninfo: fix memory leaks from pNext chains

cube/cube.c, cube/cube.cpp
=> cube: Handle SURFACE_LOST return code

cube/cube.c
VK_KHR_incremental_present requires the client to
bind to wl_compositor v4. This is because internally
some Vulkan Wayland drivers convert VkPresentRegionKHR
to wl_surface.damage_buffer() [1].
If the Wayland compositor advertises wl_compositor v4,
we can bind to it and make incremental present actually
work.
[1] https://gitlab.freedesktop.org/mesa/mesa/blob/master/src/vulkan/wsi/wsi_common_wayland.c#L862
=> cube: Try to bind to wl_compositor v4

vulkaninfo/vulkaninfo.cpp
Change-Id: I4cd38c06842c99b514b4f289f7856eb810c111f3
=> vulkaninfo: fixed spelling of properties

vulkaninfo/macOS/vulkaninfo.sh
Fixes vulkaninfo.app bundle crashing on startup.
=> vulkaninfo: Fix gitlab issue 181

scripts/vulkaninfo_generator.py
Previous versions of vulkainfo's autogen code didn't check if enums and
bitmasks from extensions were disabled, possibly letting them leak into
the generated code. This commit checks and skips any fields which aren't
supported.
Also discovered that the `for ext in extensions:` block in VulkanEnum and VulkanBitmask was never being used, and removed it as it didn't affect the generated output in the slightest. 
File changed:
scripts/vulkaninfo_generator.py
Change-Id: I0e6fd9872d9377a17797cfcf6c2fbcee649e3657
=> vulkaninfo: check that extensions aren't disabled

vulkaninfo/CMakeLists.txt, vulkaninfo/macOS/vulkaninfo/metal_view.h, vulkaninfo/macOS/vulkaninfo/metal_view.mm, vulkaninfo/vulkaninfo.cpp, vulkaninfo/vulkaninfo.h
Added functions to create a Metal Surface and report its
information.
=> vulkaninfo: Add VK_EXT_metal_surface info

cube/cube.c, cube/cube.cpp
Best practice is to leave memory mapped for the life of the app
rather than map-update-unmap
Change-Id: Iab7ff62a4ebdf47f4916f7d769d0cf3647a52d31
=> cube: Leave uniform memory mapped

icd/generated/mock_icd.cpp, icd/generated/mock_icd.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json, scripts/vulkan_tools_helper_file_generator.py, scripts/vulkaninfo_generator.py, vulkaninfo/generated/vulkaninfo.hpp, vulkaninfo/vulkaninfo.cpp
Pulling in the changes made for 1.2 and put it on the github repo
=> Rebase gitlab changes onto github

scripts/known_good.json
Update glslang commit ID from:
`ebf634bcaa3e46ca8a912ed05b87281c731b2391`
to
`4fc7a33910fb8e40b970d160e1b38ab3f67fe0f3`
=> build: Update glslang commit ID in known_good.json

vulkaninfo/vulkaninfo.h
Drastically reduces repetition and ensures consistent error handling.
=> vulkaninfo: use a helper for the two-call idiom

scripts/known_good.json
Updated MoltenVK version:
`v1.0.38` -> `v1.0.40`
=> build: Update MoltenVK version in known_good.json

vulkaninfo/outputprinter.h, vulkaninfo/vulkaninfo.cpp, vulkaninfo/vulkaninfo.h
Previously, if vulkaninfo encountered any errors, it shut down then
and there. This is bad for json output where you are left with an
invalid file. By using exceptions, vulkaninfo will catch errors,
print it to cerr, then finish off the file so its left in a valid
state.
Change-Id: I2c0116b435713df6135b9c606fa95cfadbfdf8d8
=> vulkaninfo: Refactor error handling

scripts/known_good.json
Updated the glslang commig ID in `known-good.json` to:
`bfe4c5957fc51148a0aab6e04bb22020667c1092`
=> build: Update glslang commit ID in known-good.json

scripts/known_good.json
Updated the glslang commit ID in `known-good.json` to:
`e157435c1e777aa1052f446dafed162b4a722e03`
=> build: Update glslang version in known-good.json

vulkaninfo/outputprinter.h
Change-Id: Ie4ec90d05ba5c394df5d020eecee1c061e1010ac
=> vulkaninfo: fix msvc warnings from wrapper classes

vulkaninfo/CMakeLists.txt, vulkaninfo/macOS/vulkaninfo.cmake, vulkaninfo/macOS/vulkaninfo.sh, vulkaninfo/macOS/vulkaninfo_run.command, vulkaninfo/vulkaninfo.cpp, vulkaninfo/vulkaninfo.h
Due to difficulties setting up dynamic library loading on apple,
the change to use dynamic loading has been reverted to a dynamic link.
Change-Id: If980a327aa07669cc00aa4847dd4339a0ae42804
=> vulkaninfo: dynamically link vulkan on apple

scripts/known_good.json
Removed glslang dependancy from known-good.json
=> build: Remove glslang dependancy from known-good

build-gn/generate_vulkan_layers_json.py
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1727#issuecomment-617420416
=> scripts: Sync GN json script with ValidationLayers

scripts/kvt_genvk.py
Change-Id: I5b932dc1743e78830467dac4783ac3731accb9e0
=> scripts: Add default arg for kvt_genvk directory

vulkaninfo/vulkaninfo.cpp
Change-Id: I6fafdfac5d508cb02026c4cf1d1dbf7adf866bd4
=> vulkaninfo: fix indent width for present support

scripts/known_good.json
Updated MoltenVK version in known-good.json from v1.0.41
to v.1.0.43
=> build: Update MoltenVK to v.1.0.43 in known-good.json

vulkaninfo/vulkaninfo.cpp, vulkaninfo/vulkaninfo.h, vulkaninfo/vulkaninfo.md
Shows the instance version, instance extensions, available layers,
and the following driver properties:
apiVersion, driverVersion, vendorID, deviceID, deviceType, and deviceName.
Change-Id: Iccf721af9b8a7da9b008d8879212fa1125dd0d2e
=> vulkaninfo: add `--summary` option that shows basic info

icd/generated/mock_icd.cpp, scripts/mock_icd_generator.py
@tobine @mark-lunarg PTAL. Had to update the known-good in the process.
=> Bump mock icd surface caps

vulkaninfo/outputprinter.h, vulkaninfo/vulkaninfo.cpp, vulkaninfo/vulkaninfo.h, vulkaninfo/vulkaninfo.md
Print the Properties and Features of the KHR_porability_subset.
Requires a driver which supports the extension to get any usable
output.
Change-Id: I45d0d63108f0542868207247d0e6ec42b5a84b67
=> vulkaninfo: Add json output for portability subset

cube/CMakeLists.txt, scripts/fetch_glslangvalidator.py
Allows a single worktree to be used by multiple platforms for builds.
=> build: Fix linux/windows build in single directory

vulkaninfo/vulkaninfo.cpp
Previous commit didn't contain all that were necessary.
Change-Id: I0983beb06d95dd316ece5b7ba52754e4ad180cbd
=> vulkaninfo: Add more portability macro guards

vulkaninfo/outputprinter.h
Doesn't alter current behavior.
Change-Id: I76cb0c4395741848667b2687d722b9b2245fb296
=> vulkaninfo: add option to always open details for HTML

scripts/vulkaninfo_generator.py
Multi-dimensional arrays are already in the specification and don't cause any issues for vulkaninfo
=> scripts: Remove assert for nested array types

cube/cube.c, cube/cube.cpp
=> Select physical device that supports DISPLAY WSI

cube/cube.c, cube/cube.cpp
=> Resize vkcube on SUBOPTIMAL if necessary

cube/cube.c, cube/cube.cpp
=> Fix cube compilier warnings

cmake/FindWaylandProtocols.cmake, cmake/FindWaylandScanner.cmake, cube/CMakeLists.txt, cube/cube.c, cube/cube.cpp
Addresses #469 
@mstoeckl @jbeich please review - I'm counting on your testing for this PR
=> Rebase and patch "Port Wayland impl from wl-shell to xdg-shell"

CMakeLists.txt
Added the Werror, Wall, and Wextra flags to builds in CMake.
=> build: Add Werror and warning flags to builds

cube/cube.cpp
=> Remove unused variable in vkcube

vulkaninfo/vulkaninfo.h
The VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT and
VK_IMAGE_CREATE_SPARSE_BINDING_BIT were swapped, causing erroneous output
and validation messages.
Fixes #514
Change-Id: Iff61c379f66aedb14e27e7f422516e1469274248
=> vulkaninfo: Fix image format query arguments

vulkaninfo/vulkaninfo.h
am 72c2d5f0b0e59bf429144d2e60d8fd6ce1710887
=> vulkaninfo: Fix device version check

scripts/known_good.json
Updated known_good.json file for the latest MoltenVK tag used in the 1.2.182 sdk build.
=> known_good.json updated for latest MoltenVK tag

cube/cube.cpp, cube/gettime.h, vulkaninfo/vulkaninfo.h
Made some changes for Vulkan-Tools to compile on FreeBSD.
=> vulkaninfo/cube: added support for FreeBSD

cube/cube.cpp
Expect and deny negative window dimensions.
=> cubepp: Fix gitlab 828.

scripts/update_deps.py
CMake really prefers forward slashes for everything. This commit replaces
the backslashes found from windows with forward slashes. Also updates Update_deps.py
to match VVL.
=> build: Update update_deps.py

vulkaninfo/vulkaninfo.h
Add a debug callback to vkCreateInstance to debug instance failures, since there are occasionally errors introduced
which yield validation messages that are currently being missed.
=> vulkaninfo: Use DebugReport callback

cube/cube.c, cube/cube.cpp
During tests, it's hard to determine if the --validation option is
actually working properly.  So add an option (--force_errors) to
intentionally force a few validation error messages to make sure
that validation is working properly.
=> vkcube/vkcubepp: Add option to force validation errors

icd/generated/mock_icd.cpp, icd/generated/vk_typemap_helper.h, scripts/mock_icd_generator.py, scripts/vulkan_tools_helper_file_generator.py
If the implementation reports that it supports this feature, it should
fill out VkFormatProperties3KHR properly.
=> scripts: Fix codegen to support VK_KHR_format_feature_flags2

cube/cube.c, cube/cube.cpp
Change-Id: I650958a8b2607eb3402eb6531909881d4a2ccc0f
=> Fix error messages upon failure to connect to window systems.

build-android/vulkan-headers_revision_android, icd/generated/mock_icd.cpp, icd/generated/mock_icd.h, icd/generated/vk_typemap_helper.h, scripts/generate_vulkan_wrapper.py, scripts/known_good.json, vulkaninfo/generated/vulkaninfo.hpp
=> build: Update to header 1.2.203

cube/CMakeLists.txt
=> Add build target for vkcube-wayland

cube/CMakeLists.txt
=> Add install target for vkcube-wayland

cube/cube.cpp
Fixes #421 Fixes #422 Fixes #409 Fixes #452
=> Cleanup of vkcubepp

cube/cube.cpp
Note that this PR depends on the #615 PR so it can't be merged before that one is merged.
=> Add DebugUtilsMessenger to vkcubepp

scripts/vulkaninfo_generator.py, vulkaninfo/generated/vulkaninfo.hpp, vulkaninfo/outputprinter.h, vulkaninfo/vulkaninfo.cpp, vulkaninfo/vulkaninfo.h, vulkaninfo/vulkaninfo.md
Initial commit to make the output occur, will need additional refinement.
=> vulkaninfo: Replace devsim with profile json output

cube/cube.cpp
=> cubepp: Fix regression in VK_KHR_display

cube/cube.cpp
=> cubepp: Fix wayland regression

vulkaninfo/vulkaninfo.h
* Show surface information on GGP platform.
=> Show surface information on GGP platform

vulkaninfo/CMakeLists.txt, vulkaninfo/vulkaninfo.cpp
turns out it is also available on mingw
=> win32: use _set_abort_behavior from ucrt

vulkaninfo/vulkaninfo.h
GetVectorInit could get stuck in an infinite loop if the underlying API call eternally returned
VK_INCOMPLETE. This commit makes GetVectorInit stop after 3 tries.
Fixes #674
=> vulkaninfo: Prevent infinite loops

cube/cube.c
=> cube: unbreak KHR_display with Clang

.github/workflows/build.yml, scripts/update_deps.py
Caches update_deps.py dependencies,
In particular MoltenVK since it's a huge dependency.
=> ci: Speed up MacOS builds

CMakeLists.txt, cube/cube.c, cube/cube.cpp, scripts/known_good.json
- Vulkan::Registry was removed
- vk_sdk_platform.h is deprecated
=> build: Update vulkan headers

cube/cube.c, cube/cube.cpp
This check was present in cube but wasn't added to cubepp.
Fixes #715
=> cubepp: Make sure width & height are > 0

cube/cube.cpp
As written in the title, `vkcubepp` demo is broken in Windows. When minimized, it will crash since both height and width of the window are zero.
The fix already existed at https://github.com/KhronosGroup/Vulkan-Tools/commit/602e418f5ace55b7fc67531bd1fada3a2a54ca83 . But was not ported to the C++ version. This PR does so.
=> Fixed cube.cpp crashing on Windows when minimized.

icd/generated/mock_icd.cpp, scripts/mock_icd_generator.py
closes https://github.com/KhronosGroup/Vulkan-Tools/issues/743
Adds basic support to get most Ray Tracing tests working with MockICD
=> mockicd: Add Support for testing Ray Tracing

scripts/known_good.json
Updated to the latest MoltenVK release
=> Updated MoltenVK known good version to 1.2.3

CMakeLists.txt, windows-runtime-installer/CMakeLists.txt, windows-runtime-installer/VulkanRT-License.txt.in
=> cmake: Keep VulkanRT-License.txt copyright up to date

scripts/known_good.json
Updated known good for new MoltenVK release.
=> Update known_good.json for MoltenVK 1.2.4

cube/cube.cpp
=> Fix cmd buffer/pool leak in vkcubepp

icd/generated/mock_icd.cpp, scripts/mock_icd_generator.py
Add implementation for vkGetRenderAreaGranularity.
=> icd: Add vkGetRenderAreaGranularity

icd/generated/function_definitions.h, scripts/mock_icd_generator.py, tests/icd/mock_icd_tests.cpp
In preparation for adding validation to VVL
=> Add support for VK_EXT_host_image_copy to the mock icd

vulkaninfo/vulkaninfo.h
Add public support for QNX to vulkaninfo
Sample output:
`
==========
VULKANINFO
==========
Vulkan Instance Version: 1.3.261
Instance Extensions: count = 16
===============================
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension …
=> Add public support for QNX to vulkaninfo

icd/CMakeLists.txt
=> cmake: Remove generate_icd_files

BUILD.gn
=> gn: Fix Chromium build

cube/CMakeLists.txt
Remove unused vars
Remove pointless code
Remove usage of CMAKE_LANG_FLAGS
=> cmake: Minor cube cleanup

cube/macOS/cube/cube.cmake, cube/macOS/cubepp/cubepp.cmake, mac_common.cmake
Simplifies CMake code in various places for Apple builds
=> cmake: Use XCODE variable

.github/workflows/tools.yml, CMakeLists.txt, icd/VkICD_mock_icd.json.in, scripts/generate_source.py
=> mock: Ensure VkICD_mock_icd.json uses up to date API version

CMakeLists.txt
This doesn't do anything anymore
=> cmake: Remove pointless code

icd/VkICD_mock_icd.json.in, scripts/known_good.json
=> build: Update to header 1.3.268

scripts/known_good.json
Helps improve local build performance
=> scripts: Allow parallel build of MoltenVK

CMakeLists.txt, cube/CMakeLists.txt, icd/CMakeLists.txt, tests/CMakeLists.txt, vulkaninfo/CMakeLists.txt
Easier to manage and fixes MSVC ASAN
=> Cleanup ENABLE_ADDRESS_SANITIZER

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/generate_vulkan_wrapper.py, scripts/known_good.json
=> build: Update to header 1.3.270

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, scripts/known_good.json
=> build: Update to header 1.3.271

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json
=> build: Update to header 1.3.272

scripts/vulkaninfo_generator.py, vulkaninfo/generated/vulkaninfo.hpp, vulkaninfo/vulkaninfo.cpp, vulkaninfo/vulkaninfo.h
Only include structures in pNext chains whose corresponding extensions or versions are supported.
=> vulkaninfo: Check requirements when adding to pNext chains

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json, scripts/mock_icd_generator.py, vulkaninfo/generated/vulkaninfo.hpp
- mockicd: Copy vkGetPhysicalDeviceCalibrateableTimeDomainsEXT implementation to promoted entry point vkGetPhysicalDeviceCalibrateableTimeDomainsKHR
=> build: Update to header 1.3.273

icd/generated/function_definitions.h, icd/mock_icd.h, scripts/mock_icd_generator.py
We hit a regression in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7123
This adds basic support to let us test and prevent future regressions
=> icd: Add basic VkDisplayKHR support

cube/cube.c
Since volk will load all extension function pointers, we don't need to load functions manually and that code can be removed.
=> cube: Use volk for all function pointers

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json, vulkaninfo/generated/vulkaninfo.hpp
=> build: Update to header 1.3.274

scripts/known_good.json
Simple update of known good for the latest MoltenVK (1.2.7) used in the 1.3.275.0 SDK release.
=> Update known_good.json for MoltenVK 1.2.7

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json, vulkaninfo/generated/vulkaninfo.hpp
=> build: Update to header 1.3.276

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json, vulkaninfo/generated/vulkaninfo.hpp
=> build: Update to header 1.3.277

cube/CMakeLists.txt, icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json, vulkaninfo/generated/vulkaninfo.hpp
=> build: Update to header 1.3.278

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json
=> build: Update to header 1.3.279

cube/linmath.h
This fixes bug in linmath.h unused function: quat_mul_vec3
Linmath is taken from upstream: [https://github.com/datenwolf/linmath.h](https://github.com/datenwolf/linmath.h)
Added function definition: degreestoradians
=> Update linmath to upstream.

icd/VkICD_mock_icd.json.in, icd/generated/function_declarations.h, icd/generated/function_definitions.h, icd/generated/vk_typemap_helper.h, scripts/known_good.json
=> build: Update to header 1.3.280

.github/workflows/tools.yml, scripts/vulkaninfo_generator.py, vulkaninfo/generated/vulkaninfo.hpp
Used PrintKeyValue instead of PrintKeyString by mistake.
=> vulkaninfo: Add quotes around NULL

icd/generated/function_definitions.h, scripts/mock_icd_generator.py
quick fix for https://github.com/KhronosGroup/Vulkan-Tools/pull/971
I swear `submitCount` had to be non-zero, but forgot it is valid to have an empty submit
=> icd: Fix DEVICE_LOST injection null check

cube/cube.c
=> cube: Poll wayland socket each iteration

cube/cube.c
The fix for #976 has a couple of flaws, I think.
1) The poll is unnecessary as we have an always-running main loop, it's okay to do an empty read, it won't block.
2) If the driver uses multiple threads internally, we are not guarding against a concurrent read by the driver.
3) We never flush messages to the server. Again, the driver could send messages and expect the application to flush.
Both 2) and 3) assume a sufficiently naive driver, most are more defensive than the bare minimum.
=> vkcube: Thread safe event polling

cube/cube.c
First frame should be rendered fully
=> cube: Fix incremental present

CMakeLists.txt
=> CMake: Mark dependencies mandatory

vulkaninfo/vulkaninfo.h
These surface extensions shouldn't be enabled if the metal surface extension is present. This fixes a deprecation notice the validation layers emit - as well as not provide redundant information (since the metal extension is a direct replacement for the mvk/ios extensions).
=> vulkaninfo: Fix deprecation of MVK/IOS surface extensions

cube/cube.c
Seems I tested vkcubepp's frame counter but not vkcube's...
=> cube: Fix broken framecount
