KhronosGroup/Vulkan-Tools

.travis.yml
common/android_util.cpp
common/android_util.h
common/vulkan_wrapper.cpp
common/vulkan_wrapper.h
cube/android/jni/Android.mk

This restores files that were dropped during the split.
Also migrates support files to this repo, which we will remove
from Vulkan-ValidationLayers and treat like a submodule.
With these changes, I can run build_all.sh and install_all.sh to get Cube spinning on Android.

android: Fixes for cube

---

scripts/mock_icd_generator.py

Enabled this extension and updated vkGetPhysicalDeviceProperties2KHR to
fill out the push descriptor properties struct if it's in the pNext
chain.

icd: Enable the VK_KHR_push_descriptor extension

---

BUILD.md
CMakeLists.txt
icd/CMakeLists.txt

- Use correct (icd.d) directory
- Make ICD installation OFF by default
- Fix up docs
Fixes #17

build: Fix mock ICD install issues

---

scripts/mock_icd_generator.py

Added calls to vkGetPhysicalDeviceExternal buffer, fence, and semaphore
properties that support for features and handle types.

icd: Add external buffers, fences, and semaphores

---

scripts/mock_icd_generator.py

These changes hard-code an unsupported image format, and unsupported sample count for images, and an unsupported memory type for images. These changes allow the following tests to run without skipping in the validation layers:
BindImageInvalidMemoryType
CreateImageFormatSupportErrors
CreateImageMaxLimitsViolation

icd: Hard-code unsupported image formats and memory types

---

cube/cube.c

We still had the debug report detection code in cube.  This removes
the last bits of it.
Change-Id: I09559cd56ee4779453221c810d8328cb4c864aef

cube: Remove last DebugReport

---

cube/cube.c
cube/cube.cpp

Fix for #22 
The QueueFamilyIndex fields only come into play when you want
to use an image in two or more queues from different queue
families, which cube does not do.
We've been getting lucky in that the spec says that if src and dst
indices are the same, in the previous scenario both zero, that they
are both treated as IGNORED.  Better to set them explicitly
Change-Id: I610aa8899539eeb25ca06254b88e6a6d0a2ffc97

cube: Explicitly set QueueFamilyIndex(s) to QUEUE_FAMILY_IGNORED

---

cube/cube.c
cube/cube.cpp

From the spec:
Whilst it is not invalid to provide destination or source access
masks for memory barriers used for release or acquire operations,
respectively, they have no practical effect. Access after a release
operation has undefined results, and so visibility for those accesses
has no practical effect. Similarly, write access before an acquire
operation will produce undefined results for future access,
so availability of those writes has no practical use. In an earlier
version of the specification, these were required to match on both
sides - but this was subsequently relaxed.
These masks should be set to 0.
Change-Id: I495dc86ad62c0651fbc6acbfb0dfbb8245a324be

Clean up validation errors from separate present queue

---

.appveyor.yml
.gitmodules
.travis.yml
BUILD.md
CMakeLists.txt
cube/CMakeLists.txt
icd/CMakeLists.txt
vulkaninfo/CMakeLists.txt

- Remove Vulkan-Headers submodule
- Add CMake code to add VULKAN_HEADERS_INSTALL_DIR and
VULKAN_LOADER_INSTALL_DIR to search when locating
Vulkan headers and loader
(LOADER_REPO_ROOT still being honored for now)

repo: Reorg to remove Vulkan-Headers submodule

---

CMakeLists.txt
cube/macOS/cube/cube.cmake
cube/macOS/cubepp/cubepp.cmake
vulkaninfo/CMakeLists.txt
vulkaninfo/macOS/vulkaninfo.cmake

Fixed CMake files for macOS to include the vulkan dylib loader
file in the bundles instead of the vulkan framework file.

cmake: Fix macOS CMake files to include dylib file

---

CMakeLists.txt

Rename uninstall target until downstream repos have been modified to remove submodules.  
Target is renamed to uninstall-Vulkan-Tools, this commit can be reverted once the VulkanTools repository rework is complete.
This is required to get VulkanTools working with the new repos.

Temporarily rename uninstall target

---

.appveyor.yml

- Use -A CMake argument instead of creating a generator string
based on the worker image and architecture. Instead, set the
architecture (platform Win32 or x64) with -A and take whatever
Visual Studio version is provided by the worker image.  The
worker image is specified by the "os" config property.
- Reduce jobs from 4 to 2
- Remove AppVeyor caching of the external directory; this
directory was not being used anyway.

ci: Clean up AppVeyor config file

---

cmake/Copyright_cmake.txt

Get latest Kitware copyright notice from
https://gitlab.kitware.com/cmake/cmake/blob/master/Copyright.txt @ d45d5e2

cmake: Add Kitware copyright

---

CMakeLists.txt

Updated CMake files to use MOLTENVK_REPO_ROOT as an
environment variable if no CMake argument is provided.
CMake argument takes priority over environment variable.

cmake: Update CMake to check env for MoltenVK

---

vulkaninfo/vulkaninfo.c

Fixed incorrect number of arguments in print statements
for VkPhysicalDeviceMaintenance3PropertiesKHR.

vulkaninfo: Fix warnings in maintenance3 printing

---

scripts/fetch_glslangvalidator.py

Changed urllib.request.urlretrieve to
urllib.request.urlopen and set to not check SSL
Fixes issue #51

script: Fix fetch_glslangvalidator.py SSL error

---

vulkaninfo/vulkaninfo.c

Messages emitted from the DbgCallback function were previously sent to stdout. These messages are now sent to stderr and no longer affect the validity of json output.

vulkaninfo: Remove warning messages from json output

---

cube/cube.c
cube/cube.cpp

As of Vulkan-ValidationLayers commit 2872f4a, the layers now check that
image layouts specified in descriptors match the current image layout
state.  LAYOUT_GENERAL is not a wildcard for this matching.
Change the image layouts for the combined image sampler descriptors
from LAYOUT_GENERAL to LAYOUT_SHADER_READ_ONLY_OPTIMAL.

cube: Fix new validation error

---

cube/cube.c
cube/cube.cpp

This PR proposes ignoring the erases to the window in the cube app. 
When resizing the window the erases and the Draw() get called intermittently which causes a flashing effect to occur.

The window erases and draws cause flashing when resizing

---

scripts/mock_icd_generator.py

VK_SUCCESS is not a valid return value for this function.  VK_EVENT_SET
is used instead.

mock_icd: fix vkGetEventStatus output

---

cube/cube.cpp

Add explicit casts for nullptr values passed to vulkan.hpp so the correct function overload is selected.

demos: Fix cubepp with latest vulkan.hpp

---

scripts/vulkan_tools_helper_file_generator.py

The 1.1.90 header introduced the use of "\textrm" in `vk.xml`, requiring
changes to `scripts/vulkan_tools_helper_file_generator.py`

scripts: Extend scope of LaTeX handling

---

BUILD.md
CONTRIBUTING.md
README.md
build-android/build_all.sh
build-android/install_all.sh
cube/CMakeLists.txt
cube/android/cube-with-layers/AndroidManifest.xml
cube/android/cube-with-layers/custom_rules.xml
cube/android/cube-with-layers/res/values/strings.xml
cube/android/cube/AndroidManifest.xml
cube/android/cube/custom_rules.xml
cube/android/cube/res/values/strings.xml
cube/android/jni/Android.mk
cube/android/jni/Application.mk
cube/macOS/cube/Info.plist
cube/macOS/cube/cube.cmake
cube/macOS/cubepp/Info.plist
cube/macOS/cubepp/cubepp.cmake
scripts/fetch_glslangvalidator.py

Move to a more consistent naming scheme for Vulkan apps.

Rename cube and cubepp exes to vkcube and vkcubepp

---

cube/CMakeLists.txt

Changed fixup_bundle pointing at cube.app and
cubepp.app to point to vkcube.app and vkcubepp.app

cube: Fix fixup_bundle not set to proper cube

---

cube/macOS/cube/cube.cmake
cube/macOS/cubepp/cubepp.cmake
scripts/known_good.json
vulkaninfo/macOS/vulkaninfo.cmake

Update MoltenVK commit ID in known_good.json
and modified CMake files for cube, cubepp, and
vulkaninfo to accomidate the new file structure
of the MoltenVK repo.
Note: Updated Vulkan-Loader in known_good.json to pick up a fix for a problem where MacOS bundles would crash at the loader level.

build: Update MoltenVK commit and CMake files

---

vulkaninfo/vulkaninfo.c

Additional spacing cleanup in the surface capabilities section.
I mentioned these changes in #95, only to realize it had already been pulled minutes before.

vulkaninfo: More spacing cleanup

---

vulkaninfo/vulkaninfo.c

Removed the extra line breaks appearing after
certain data structures listed in the HTML output
file of Vulkan Info.

vulkaninfo: Fix extra lines in HTML file

---

vulkaninfo/vulkaninfo.c

- Clear the structures allocated for the pNext chains.  While this
is not strictly necessary, any pNext structure that is not
filled in by a driver (because the extension isn't there) gets
left in an untouched state.  This can be a false positive flagged
by valgrind.
- Use XFree to free storage allocated by Xlib's XGetVisualInfo().
This fixes an actual leak.

vulkaninfo:  Fix memory init/leak

---

vulkaninfo/vulkaninfo.c

Fixes issue #72 , which prevented vulkaninfo from
listing image formats past
VK_FORMAT_ASTC_12x12_SRGB_BLOCK for Vulkan 1.1

vulkaninfo: Fix issue 72

---

vulkaninfo/vulkaninfo.c

Added VK_EXT_pci_bus_info extension to Vulkan Info.
Print data from struct
VkPhysicalDevicePCIBusInfoPropertiesEXT.

vulkaninfo: Add VK_EXT_pci_bus_info

---

vulkaninfo/vulkaninfo.c

vulkaninfo must not query formats that are not supported on a
given instance, as this provokes undefined behavior (it could
appear to work, or it could segfault in the driver).
These changes ensure that a format is only queried if it
is supported in either the base Vulkan instance or, if it is an
extension format, if that extension is supported by the Vulkan
instance.
- Moved instance version information to the AppInstance struct
(initialized by AppCreateInstance()), which makes sense and
allows lower-level code to determine whether a format is
supported on the current instance version
- Formats are now encoded with their owning Vulkan version
and extension name, so they can be checked for validity
before making a query.
Note that this change can cause behavior changes; instances
that …

vulkaninfo: only query supported formats

---

vulkaninfo/vulkaninfo.c

Added the following extensions and structures
to the Vulkan Info output:
VK_KHR_shader_atomic_int64:
VkPhysicalDeviceShaderAtomicInt64FeaturesKHR
VK_EXT_transform_feedback:
VkPhysicalDeviceTransformFeedbackFeaturesEXT
VkPhysicalDeviceTransformFeedbackPropertiesEXT
VK_EXT_scalar_block_layout:
VkPhysicalDeviceScalarBlockLayoutFeaturesEXT
VK_EXT_fragment_density_map:
VkPhysicalDeviceFragmentDensityMapFeaturesEXT
VkPhysicalDeviceFragmentDensityMapPropertiesEXT

vulkaninfo: Add extensions

---

vulkaninfo/vulkaninfo.c

We didn't quite get the check on whether a format can be legally
queried on a particular GPU quite right.  We were checking against
the instance version only.  We need to check agains the driver's
supported API version as well.

issue 126: fix vulkaninfo segfault on 1.0 devices

---

vulkaninfo/vulkaninfo.c

It doesn't make sense to enforce clang-format rules
and then turn it off for more than half of the file.
Removed `clang-format off` from vulkaninfo.c and ran
clang-format to clean up the code.
closes #124

vulkaninfo: Remove clang-format off

---

vulkaninfo/vulkaninfo.c

Four extensions, if supported on a device, didn't emit the proper "</details>"
closing tag.  This caused the nesting to be incorrect while viewing the HTML output.

vulkaninfo: fix nesting of HTML output

---

scripts/common_codegen.py

In `common_codegen.py` the Metal platform was defined without the "_EXT"
suffix

build: Correct Metal platform name

---

vulkaninfo/vulkaninfo.c

This reports for Memory Types which Images they are usable with (via `vkGetImageMemoryRequirements`).
Currently it works only for images, and outputs only the `human_readable` text.
I want to solicit some input:
1) What would be the best (better) output format
2) What would be the best json (for device simulation)
3) There's bit of a combinatorial explosion of `usage`x`flags` for buffers. Any ideas how to handle that and present it to the user?

vulkaninfo: Report images compatible with memory type

---

vulkaninfo/vulkaninfo.c

Fixed the HTML output for the
VkPhysicalDeviceDepthStencilResolvePropertiesKHR
structure.
HTML output was being sent to the terminal instead of
the HTML file.

vulkaninfo: Fix HTML output

---

.appveyor.yml
.travis.yml

Updates to other repos can cause errors to propagate
from changes that have nothing to do with PRs on
Vulkan-Tools.
This commit changes cloud CI systems to build with
known_good.json in Vulkan-Tools so that issues
affecting other repos do not prevent PRs in Vulkan-Tools
from getting merged.

test: Update cloud CI to use known_good.json

---

vulkaninfo/vulkaninfo.c

Not all ICDs support all the surface extensions that vulkaninfo
enumerates.
For example, on Linux with an ICD that only support VK_KHR_xcb_surface,
vulkaninfo crashes:
Presentable Surfaces:
=====================
ERROR: VK_KHR_xlib_surface extension not enabled.  vkCreateXlibSurfaceKHR not executed!
vulkaninfo/vulkaninfo.c:1427: failed with VK_ERROR_EXTENSION_NOT_PRESENT

vulkaninfo: Check support for surface extensions before using them

---

vulkaninfo/vulkaninfo.c

Checks to make sure surface extensions were enabled
neglected to leave important struct variables outside
the if statements.
This resulted in these variables becoming uninitialized
and causing undefined behavior.

vulkaninfo: Fix crash at Presentable Surface

---

cube/cube.c

Allocated memory is not freed after being used. This causes memory leak.

Fix memory leak in `vkcube`.

---

.gn
.travis.yml
BUILD.gn
build-gn/DEPS
build-gn/generate_vulkan_layers_json.py
build-gn/secondary/build_overrides/build.gni
build-gn/secondary/build_overrides/vulkan_tools.gni
build-gn/update_deps.sh
scripts/kvt_genvk.py

Add support for GN, Google's meta-build system for Ninja: https://gn.googlesource.com/gn/
- Pull GN build into the repo to ease update process for consumers of Vulkan-Tools who use GN.
- Add a non-blocking Travis CI job to monitor for breakages
- Currently only MockICD is supported, more targets can be added as needed by downstream projects

Port GN build from ANGLE and add CI

---

.appveyor.yml
.travis.yml
scripts/update_deps.py

These changes ensure that the Travis and AppVeyor
builds use a known version of CMake.

cmake: Use CMake 3.10.2 for CI

---

vulkaninfo/vulkaninfo.c

Fixes an issue found where the device properties
and extensions would only be printed for the first GPU
on a system when printing in HTML format.

vulkaninfo: Fix HTML format for multi-GPU computer

---

cube/cube.c

Add format string to sprintf call

cube: Fix compiler warning

---

cube/cube.c
cube/cube.cpp

Because the contents of the depth buffer don't need to be preserved, a mere execution barrier should be sufficient.   @cforfang do the barrier stage masks look ok to you?

cube: Use barrier to sync depth buffer

---

vulkaninfo/vulkaninfo.c

Vulkaninfo was replacing function `snprintf`
with function `_snprintf` on windows.
This seems to be for backwards compatiblity
with VS2013.
`_snprintf` is considered deprecated in VS2015
as `snprintf` is properly implemented.
Since we are dropping compatibility with VS2013 it
seems like this replacement can be removed.
Complete removal of the pre-processor command
that replaces `snprintf` with `_snprintf` seems to cause
problems with AppVeyor.  Instead I now replace `snprintf`
with `_snprintf_s`.
Hopefully a future commit can remove this completely.
Fixes #202

vulkaninfo: Fix issue 202

---

vulkaninfo/vulkaninfo.c

It was suggested that `.maxComputeSharedMemorySize`
from VkPhysicalDeviceLimits be displayed as a decimal
instead of a hex number.
Fixes issue #195.

vulkaninfo: Fix issue 195

---

vulkaninfo/vulkaninfo.c

Issue #207 mentions that one of the main problems users
encounter when troubleshooting is a failure to create a
Vulkan instance, and suggests that a statement be added
to this error message that describes the most common
causes of this problem.
This commit adds this additional statement to the current
error message.
Closes #207

vulkaninfo: Add more descriptive error message

---

cube/cube.c

vprintf (not printf) must be used with va_list.
Also moved flush() outside the va_list's scope.
Change-Id: Ib82b9f7e7ec1f954619c3eadb8dcaeb08abf113a

cube: Fix DbgMsg() use of varargs

---

scripts/known_good.json

Modified MoltenVK build arguments for MacOS from
`MVK_LOGGING_ENABLED=0` to `MVK_CONFIG_LOG_LEVEL=1`.
This allows users to set the logging information they
want when an application is run using MoltenVK.
By default, only errors are logged.
Fixes [LunarXchange Issue #862](https://vulkan.lunarg.com/issue/view/5d18ef0686da81065fffeb52)

build: Fix LunarXchange Issue 862

---

scripts/mock_icd_generator.py

Spec mandates that at least VK_RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR be
supported for supportedDepthResolveModes and
supportedStencilResolveModes

scripts: Add required depth/stencil resolve props

---

cube/cube.c
cube/cube.cpp

Latest version of MoltenVK behaves in an apparently non-conformant way
by not allowing some linear images to be mapped to memory with
VK_MEMORY_PROPERTY_HOST_COHERENT_BIT.  This change sidesteps the issue
by forcing the use of staging buffer for loading textures.

Workaround macOS cube issue

---

vulkaninfo/vulkaninfo.c

Fixes incorrect html output from a forgotten html closing tag.
Change-Id: I3e731dafc0b191dfaa71426a7a88b6ccd28477c2

vulkaninfo: fix forgotten </details> tag

---

scripts/known_good.json

MoltenVK seems to have trouble building on the
current version of Vulkan-Headers.
Since Vulkan-Headers doesn't take very long to build and
changes often, this fix removes the reuse of the
Vulkan-Headers repo, whose version is provided by Vulkan-Tools
known-good.json, in the MoltenVK build.
It instead uses the version of Vulkan-Headers provided by
the MoltenVK known-good when building MoltenVK.
**Note:** Vulkan-Tools and other required repos are still
built with the version of Vulkan-Headers provided by
Vulkan-Tools known-good.json.

build: Fix known-good MoltenVK building

---

vulkaninfo/vulkaninfo.c

Fixes issue #227 where vulkaninfo on MacOS would
seemingly repeat the same 4 formats 8 times each.
This was simply the function AppDumpSurfaceFormats listing
only the VkFormat attribute from VkSurfaceFormatKHR and not
the VkColorSpaceKHR attribute.

vulkaninfo: Fix Issue 227

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

A slight oversight in the output meant there were extra newlines
in pNext chain traversal.
This makes sure only one newline is printer per item in the chain.
files modified:
- vulkaninfo/generated/vulkaninfo.hpp
- scripts/vulkaninfo_generator.py
Change-Id: I3b3cac55c3e90d0b3f59e70fab9c4f56473c6dd6

vulkaninfo: fix extra newlines

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Previously if the device didn't support VK_KHR_device_group vulkaninfo
would not catch it and subsequently crash. This commit adds error
checking and bool flag to GetGroupCapabilities for callers to know
if it was successful.
files modified:
- vulkaninfo/vulkaninfo.h
Change-Id: Ie8fe9cc46ebe0fa6cae9985d89628d60ddf58cf2

vulkaninfo: Handle device group extension not available

---

vulkaninfo/vulkaninfo.cpp

On windows the console window will immediately close after running
vulkaninfo, this fixes it.

vulkaninfo: Fix closing immediately on windows

---

vulkaninfo/macOS/vulkaninfo.cmake

Fixes MacOS crash while building the Vulkaninfo.app bundle.

build: Fix Vulkaninfo Bundle build on MacOS

---

vulkaninfo/vulkaninfo.cpp

Currently, the json option doesn't specify that it only outputs for one
gpu and that it follows a schema. This adddresses that. In the future
there might be a PR which lets json output multigpu and all the same 
info as text/html, but for now its important to document the current state.
file changed
Change-Id: I3af8d559b2464d7ce00ce21e58a1c3054c0740b4

vulkaninfo: updated json documentation

---

cube/cube.c
cube/cube.cpp

During the release of the 1.1.114 MacOS SDK, a workaround
for vkcube was needed to get it functioning in time for release.
The underlying problem has since been fixed, and this workaround
is not longer necessary.

cube: Revert 1.1.114 SDK workaround for vkcube

---

vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp

Several places in the output code of vulkaninfo had preconditions,
like the indent level being zero or positive, but had no asserts
checking the value. This commit adds such defensive measures, as well
as a reordering IndentIncrease to be correct in regards to keeping
indents zero or above. There also is a refactor of the GpuDumpFormatProperty
function so it handles the various output formats on its own, instead of being
split among caller and callee.
files modified
- vulkaninfo/outputprinter.h
Change-Id: Iafa03193407229d345f550c4c4c3a9dd1e235919

vulkaninfo: Added asserts to check output

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

If a machine has multiple surface types that work with the
same gpu and have the same properties, vulkainfo will now
list them in a short array instead of duplicating the entire
surfaces information. To do this required being able to compare
vulkan objects, necesitating the autogeneration of comparators
for vulkan structs. This patch also refactors some of the
device creation code to better reflect the actual data
dependencies of the various vulkan objects.
files modified
- vulkaninfo/vulkaninfo.h
- scripts/vulkaninfo_generator.py
- vulkaninfo/generated/vulkaninfo.hpp
Change-Id: Ifda51eacc3883982a6e2f7f60439827eb355c204

vulkaninfo: Present Surfaces now wont show duplicates

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Previous versions, in win32 would sleep infinitely if a crash occured. 
This commit will first check if its a text output first before sleeping, to preserve 
the error if it is in a console but return immediate if it isn't.
Change-Id: Ib1b43001e970c8c3114e666d96b24dc3c557a579

vulkaninfo: fix infinite sleep for non text outputs

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.md

The indented behavior was to only show format properties if requested
for text output and always show them for html & json. This commit
modifies the --help output and documentation to better reflect this
behavior.
files modified
- vulkaninfo/vulkaninfo.md
Change-Id: I5e35b8af2db74c37dfadf669ffc81e69304fc4e0

vulkaninfo: added more documentation for show-formats

---

vulkaninfo/vulkaninfo.h

Calling xcb_disconnect on the connection to release memory and
return.
Otherwise on a headless display with no X11 backend the nullptr
for the connection will cause segmentation fault on following
xcb calls when xcb_connection_has_error returns a code.
examples ran on headless displays
DISPLAY=:0 vulkaninfo returns XCB_CONN_ERROR
DISPLAY=foobar vulkaninfo returns XCB_CONN_CLOSED_PARSE_ERR
Signed-off-by: Daniel Charles <daniel.charles@intel.com>

vulkaninfo: return properly on xcb onnection errors

---

cube/cube.c
cube/cube.cpp

Modified viewport creation in vkcube to keep the
aspect ratio square and centered.
This change prevents cube from squishing and warping
when the window is resized.
It now shrinks and grows.

vkcube: Fix Cube Squishing on Resize

---

cube/CMakeLists.txt
cube/cube.c
cube/cube.cpp
cube/macOS/cube/DemoViewController.m
cube/macOS/cubepp/DemoViewController.mm

Made DemoViewController.m compatible with VK_EXT_metal_surface
extension and replaced all references
to VK_MVK_macos_surface and VK_MVK_ios_surface with
VK_EXT_metal_surface.
PR #220 cherry-picked and rebased onto master.
I also modified vkcubepp to use VK_EXT_metal_surface.

vkcube: Replace MoltenVK surfaces with Metal

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Instead of depending on user32.dll, this library is
now loaded dynamically.
This change is needed to redistribute vulkaninfo.exe
as a part of "universal" windows driverm, by making
vulkaninfo pass the 'ApiValidator' test.
See more here https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/validating-universal-drivers
Author: Kamil Szypryt <kamil.szypryt@intel.com>

vulkaninfo: load user32.dll dynamically

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

This commit removes several spurious wanings msvc would display, like implicit conversions for VkBool32 to bool and several signed/unsigned comparisons.
Change-Id: Id485c044575105ec52fd49f9f0c5881674841a8e

vulkaninfo: reduced spurious warnings for msvc

---

vulkaninfo/generated/vulkaninfo.hpp

The PR to reduce spurious warnings while using MSVC didn't include
updating vulkaninfo.hpp. This commit runs generate_vulkaninfo_hpp
to get the most up to date version.
Change-Id: I1ff352bce121872a72002d6650ed38b330d4a61f

build: update vulkaninfo.hpp to fix windows build warnings

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Previously, vulkaninfo would hard crash if device groups failed
the call to vkEnumeratePhysicalDeviceGroupsKHR. If an error happens
now the GetGroups call simply returns an empty vector.
Files Modified:
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h
Change-Id: I60ed002161523cede53a144be3fad1d4bb0dd1f1

vulkaninfo: safely handle device groups not supported

---

vulkaninfo/vulkaninfo.cpp

Before when using the --json=X flag, if X was out of range it would
default to the first gpu. Now it emits an error and exits.
modified:   vulkaninfo/vulkaninfo.cpp
Change-Id: I0df1100f7ccc6ca37069f7798f3b620efc9a8bee

vulkaninfo: exit on invalid gpu selected

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Previously, the printing logic stored surface names in a vector.
By switching to a set, this stops surface names from being listed
multiple times.
Files modified:
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h
Change-Id: I5bf2acfd773c0fef6d17d21d3a489cc30df72e4d

vulkaninfo: Make presentation surface names a set

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Added support for the VK_EXT_tooling_info extension.
Files modified:
modified:   scripts/vulkaninfo_generator.py
modified:   vulkaninfo/generated/vulkaninfo.hpp
modified:   vulkaninfo/vulkaninfo.cpp
modified:   vulkaninfo/vulkaninfo.h
Change-Id: I9fc4e239b37fdff9ecdba4bf947a0b5d57d06745

vulkaninfo: Support VK_EXT_tooling_info

---

vulkaninfo/vulkaninfo.md

Due to IVH's shipping their own version of vulkaninfo through
the vulkan runtime package, the vulkaninfo binary included in the
Windows Vulkan SDK was renamed to `vulkaninfoSDK.exe` to prevent
name conflicts. This commit fixes the lack of documentation in the
readme about the change
modified:   vulkaninfo/vulkaninfo.md
Change-Id: I7533eaa4ee5a915b36324f40a9ba4ced785710ff

vulkaninfo: update readme for Windows SDK name change

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

In the commit to reduce unecessary surfaces being listed where only the surface extension differed, the which gpu the surface was using wasn't considered, creating a matrix of surfaces, when there should of been only 1. This fixes it by making sure to only collate surface extensions if they share a GPU.
Change-Id: Ib0d17a229713b3e4cec6f2885f81c96c5232ee0b

vulkaninfo: erroneous presentation surfaces

---

vulkaninfo/outputprinter.h

The output printers for UUID and LUID wouldn't retain the leading zero's,
leading to an inaccurate hex string.
modified:   vulkaninfo/outputprinter.h
Change-Id: I0834c00ca810d67a2849cdfb0a46db5e70158376

vulkaninfo: Fix UUID printing

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

Tooling info added flags for different purposes, however they let the debug utils, debug report
and debug marker extensions use the same bitpos values for the same flags.
The autogen didn't consider this possibly, and would output the flags multiple times.
modified:   scripts/vulkaninfo_generator.py
modified:   vulkaninfo/generated/vulkaninfo.hpp
Change-Id: I7c7a648d9051f8ce2876083dfb0d2ddc2eb7ca95

vulkaninfo: remove duplicate flags/bitmasks

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

vulkaninfo would previously use the instance version for determining
what capabilities to display. This leads to issues when running a 1.2
loader on a 1.1 or 1.0 driver.
modified:   vulkaninfo/vulkaninfo.cpp
modified:   vulkaninfo/vulkaninfo.h
Change-Id: I7f12c10d48f99d429025337b00c677936a040d13

vulkaninfo: use gpu version instead of instance

---

vulkaninfo/vulkaninfo.md

Fixed various markdown-lint errors and moved the note about
vulkanSDK.exe to near the top of the document.
Change-Id: I2025ef27ffb3ad27469dd903db9c2c1e04929708

vulkaninfo: update readme, move vulkansdk.exe note

---

vulkaninfo/vulkaninfo.h

When the original vkEnumerateInstanceVersion was implemented, the loader always return
0 for the patch. This has since been corrected, but in the mean time vulkaninfo used the
hardcoded VK_HEADER_VERSION to get the patch information. Now vulkaninfo will use the
patch version from the instance, unless it is zero, in which it will then fallback
to VK_HEADER_VERSION's patch.
modified:   vulkaninfo/vulkaninfo.h
Change-Id: If0a63534253afadccbad50c6256cdef8016222c1

vulkaninfo: use patch version from instance

---

cube/CMakeLists.txt

```
CMake Error at cube/CMakeLists.txt:177 (CHECK_LIBRARY_EXISTS):
Unknown CMake command "CHECK_LIBRARY_EXISTS".
```
I'm running into this error when building with:
```
cmake -DCMAKE_COLOR_MAKEFILE:BOOL=TRUE -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=None -DCMAKE_C_FLAGS:STRING=-march=native -O2 -pipe -DCMAKE_CXX_FLAGS:STRING=-march=native -O2 -pipe -DCMAKE_AR:PATH=x86_64-pc-linux-gnu-ar -DCMAKE_RANLIB:PATH=x86_64-pc-linux-gnu-ranlib -DCMAKE_NM:PATH=x86_64-pc-linux-gnu-nm -DCMAKE_C_COMPILER:PATH=x86_64-pc-linux-gnu-cc -DCMAKE_CXX_COMPILER:PATH=x86_64-pc-linux-gnu-c++ -DCMAKE_INSTALL_PREFIX:PATH=/usr/x86_64-pc-linux-gnu -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-pc-linux-gnu -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM:STRING=NEVER -DCMAKE_SYSTEM_PREFIX_PATH:PATH=/usr/x86_64-pc-linux-gnu …
```

vkcube: fix unknown CMake command error

---

vulkaninfo/vulkaninfo.cpp

Previously, vulkaninfo assumed the surface counter and surface capabilities 2 extensions were
supported. Now it correctly checks for them.
Files modified:
vulkaninfo/vulkaninfo.cpp
Change-Id: Ia5a8e22fd062f555d60ca0ebf27e06afbb1bb8cc

vulkaninfo: Check for surface extensions

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

This commit adds a new backend, full_json, that prints the same information
as the text & html versions. This output will be used in vkconfig.
To enable the output, use the `--full-json` flag from the command line.
Many parts of the code needed refactoring to handle the json_full output.
Replacing PrintElement with PrintString, requiring StartObject instead of
StartArray, and removing many branches to make the code simpler to read.
json_full does not nest json objects within json arrays, thus keeping every
non-leaf node of a json object named.
files modified
- scripts/vulkaninfo_generator.py
- vulkaninfo/generated/vulkaninfo.hpp
- vulkaninfo/outputprinter.h
- vulkaninfo/vulkaninfo.h
- vulkaninfo/vulkaninfo.md
Change-Id: I33d036a75b65942db1ad62b2a1e0c341a2b5e36c

vulkaninfo: new vkconfig_outptut backend

---

vulkaninfo/vulkaninfo.h

The vulkan spec deprecated usage of the BEGIN END and RANGE enum values in
the vulkan headers, thus necessitating a removal of those features in
vulkaninfo. This commit also adds the ASTC_HDR formats which were missing.
Change-Id: I56998cfddd647865e4078351e30e9687d6449fb9

vulkaninfo: Update VkFormat ranges

---

vulkaninfo/vulkaninfo.h

Certain surface capabilities were being used in a comparison
while unintialized if certain extensions were not supported.
Change-Id: Iaa858a43a1b8bc0a2b42897d2d36a3630a474450

vulkaninfo: Fix uninitialized surface capabilities

---

.travis.yml
vulkaninfo/CMakeLists.txt
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

This commit makes it so that vulkaninfo will not statically link to the vulkan
loader dll. This is to satisfy the Microsoft ApiValidator requirements.
Change-Id: Ibac46dd13df9568e9a97ce1ba4e50613902848a1

vulkaninfo: dynamically load vulkan

---

build-gn/generate_vulkan_layers_json.py

json.dump() returns a string. Writing strings to a file opened in binary mode doesn't work. Python 2 doesn't properly distringuish bytes and strings.
Open in non-binary mode, so this code works on both.

generate_vulkan_layers_json.py: Fix Python 3 compatibility

---

cube/cube.cpp

The C++ Vulkan headers will default initialize objects, not need to memset it.
Change-Id: Icdc5cde13410bc7f0002c2d6d4075e79100fd86d

cube: Remove redundant memset

---

vulkaninfo/vulkaninfo.h

During the Error Handling refactor, this line was accidentally made throwing when before
it simply reported an issue and kept going.
Change-Id: Ia3b33749ee05037a5df22398ba8b628811fad29b

vulkaninfo: Fix lack of display throwing on linux

---

CONTRIBUTING.md
scripts/check_code_format.sh

Updated `CONTRIBUTING.md` with the Travis version of clang-format:
`5.0.0` -> `7.0.0`
Added output to `.travis.yml` and `check_code_format.sh` too tell the
user the version of clang-format used by Travis CI.

format: clang-format updates

---

cube/cube.c

Pick some common non-SRGB formats first. Some drivers such as RADV expose SRGB formats first which causes incorrect rendering otherwise.

cube: Pick non-SRGB surface formats first

---

vulkaninfo/macOS/vulkaninfo.cmake
vulkaninfo/macOS/vulkaninfo.sh
vulkaninfo/macOS/vulkaninfo_run.command

The change of vulkaninfo to dlopen the loader broke the app bundle.
This commit fixes it by manually setting up DYLD_LIBRARY_PATH before
starting vulkaninfo, ensuring that it can be found.

vulkaninfo: fix app bundle not finding loader

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

PDev created at EnumPhysDevices time, but destroyed at DestroyInstance-time. This crashes when mixing Create/DestroyInstance calls as EnumPhysDevices is not required to be called.

Make Mock ICD physical device static

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

- add missing lock
- return correct values via return and count
- bump to two images
- make it return the same image handles for the same swapchain

icd: Fix vkGetSwapchainImages behavior

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Save the size of memory allocations. If a vkMapMemory is called on a
known allocation with VK_WHOLE_SIZE, then map based on the actual size
of the allocation.

mockicd:Track memory allocation size

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Reup of #368 
- add missing lock
- return correct values via return and count
- <s>bump to two images</s>
- make it return the same image handles for the same swapchain

icd: Fix vkGetSwapchainImages behavior reup

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

It helps tools that imbue the `VkPhysicalDevice` with other state via a `std::unordered_map`, such as the devsim layer.

icd: Make VkPhysicalDevice unique

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

4 bytes is  too small for many format. It causes fail in some situation.
32 bytes is the biggest size in the whole format, so it should be better.

icd: Set texel size is 32

---

vulkaninfo/vulkaninfo.h

Fixes #385
Cause: 
```c
if (!first && platforms_support_present != surface_ext.supports_present) {
is_present_platform_agnostic = false;
platforms_support_present = surface_ext.supports_present;
}
```
should be 
```c
if (!first && platforms_support_present != surface_ext.supports_present) {
is_present_platform_agnostic = false;
}
platforms_support_present = surface_ext.supports_present;
```
Change-Id: I4d01c5a9b3eb6809a732cd994854a06fee49a24c

vulkaninfo: fix queues not reporting presentation

---

vulkaninfo/vulkaninfo.h

Fixes error when VK_KHR_surface_protected_capabilities
is enabled with Vulkan 1.0

vulkaninfo: Meet extension version dependencies

---

cube/cube.c

Enum is removed in 1.2.140 headers.

Remove dependency on VK_DYNAMIC_STATE_RANGE_SIZE in vkcube

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

The memory image support code was one of the areas mostly left alone by the refactor last fall. The first commit rewrites the code to be more understandable and to use the output mechanisms introduced by the refactor.
The second commit fixes an issue where linear images were using erroneous image usage flags, namely the VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT which is not applicable to linear images.
Fixes #361

vulkaninfo: memory image support refactor and fix linear tiled images

---

.gitattributes
scripts/generate_source.py
scripts/kvt_genvk.py
scripts/vulkaninfo_generator.py
vulkaninfo/CMakeLists.txt
vulkaninfo/generated/vulkaninfo.hpp

Previously, to update the autogen for vulkaninfo required running a
separate cmake target. This commit puts it all into the same target
for ease of maintenance.
Fixes #356 
Change-Id: I98e35b01ee164e9917564f6b603e4a78c6138041

vulkaninfo: use generate_source.py for autogen

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Mock ICD supports Vulkan 1.1 but was only returning 1.0.
Fixing this.

icd:Correctly Support Vulkan 1.1

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Use a single constant, kSupportedVulkanAPIVersion, everwhere
that supported API version is referenced. Current value is
VK_API_VERSION_1_1.

icd: Cleanup supported VK API version

---

vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp

Made the 'usable for' auto expand in html as well.
Change-Id: I97d22fc6b8f603be314e13b46fe675a199c8b7eb

vulkaninfo: fix output style for memory types

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

Previously the codegen would reorder structs as it pleased.
This commit fixed several instances of bad ordering or lack thereof.
Change-Id: Ieda89c64f7400b807407c2fd26660fea10e2bb59

vulkaninfo: fix ordering issues in generated code

---

scripts/mock_icd_generator.py
scripts/vulkan_tools_helper_file_generator.py
scripts/vulkaninfo_generator.py

These changes are in preparation for the upcoming header update.
When calling in the vulkan header python generator the options have
changed in 1.2.142 which causes the options passed by the tools to be
off by one. This ends up setting the emitExtensions to the value of the
sortProcedure and eventually causes the script to fail.
This CL updates the tools to used named parameters for the generator so
that the addition of the genpath does not throw off the parameter
positioning.
Change-Id: I580d5f07ec3ff9e523dbf738561c2e53cfd42796

scripts: Use named params for generator options

---

cube/cube.c
cube/cube.cpp

Add option to select phys device to vkcube /  vkcubepp

---

vulkaninfo/vulkaninfo.h

vkconfig exposed an issue in the vulkan-loader which resulted in two different sizes
returned from vkEnumerateDeviceExtensionProperties(). A full fix requires a change to
the loader, but this commit stops the issue from happening in vulkaninfo. The issue is
because the count might be less on the second enumerate call, so resizing the vector
again trims the extraneous elements away.
Change-Id: I808d1fd13868711675aae5c91ea5100ec8cbc316

vulkaninfo: fix device ext list having bad items

---

BUILD.gn

These missing header dependencies were picked up by ANGLE's export
targets script.
@tobine fyi

Update GN to include header dependencies.

---

cube/macOS/cube/cube.cmake
cube/macOS/cubepp/cubepp.cmake
scripts/known_good.json
vulkaninfo/macOS/vulkaninfo.cmake

Minor changes to cmake files for macOS only builds. Changes to MoltenVK required some simple path changes to locate the dynamic library.

Fixed paths for MoltenVK changes

---

vulkaninfo/vulkaninfo.cpp

Whlie the main bits were properly guarded, several places should of
been which weren't, including a VK_EXT_NAME which caused compilation
to fail if VK_ENABLE_BETA_EXTENSIONS wasn't defined.
Change-Id: Ifa40f903c4affbf0c169076d9fe5dca522f82db4

vulkaninfo: properly macro guard the portability features

---

icd/generated/mock_icd.h
scripts/mock_icd_generator.py

Don't report VK_KHR_portability_subset as being supported.
Change-Id: I84fa925cee23d3a28ca2726972cb9820c03c619c

mockicd: Remove VK_KHR_portability_subset

---

cmake/FindVulkanHeaders.cmake
cmake/FindXCB.cmake

Silences two cmake verbose warnings as reproduced with `cmake-3.18.4`.
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
The package name passed to `find_package_handle_standard_args`
(VulkanRegistry) does not match the name of the calling package
(VulkanHeaders).  This can lead to problems in calling code that expects
`find_package` result variables (e.g., `_FOUND`) to follow a certain
pattern.
Call Stack (most recent call first):
cmake/FindVulkanHeaders.cmake:65 (find_package_handle_standard_args)
CMakeLists.txt:97 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
The package name …
```

cmake: Silence warnings.

---

vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp

The json schema includes an array of extensions, yet vulkaninfo was not
printing them. This commit remedies that.
Change-Id: I4ae8627660f16d7c831704ba4b082870b5e62bb5

vulkaninfo: Make json output print extensions

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Work in progress. Modifications to support use from iOS where console output is not available, but json and portability output is directly captured to .json files. For iOS, main() is now vulkainInfoMain() and is called from an iOS host GUI process still in development.

vulkaninfo: WIP: Modified for use from iOS

---

vulkaninfo/vulkaninfo.h

vulkaninfo was triggering
VUID-vkGetPhysicalDeviceSurfaceCapabilities2KHR-pNext-02671 by not adding a
`VkSurfaceFullScreenExclusiveWin32InfoEXT` in the pNext chain of
`VkSurfaceCapabilitiesFullScreenExclusiveEXT`. This commit fixes it by adding
the struct and filling in `HMONITOR` with the 'current monitor' as gotten by
`MonitorFromWindow()` with a default of using the primary monitor.
Change-Id: I025f66ef8e2d47ebb29ccd7361d3d162c644de09

vulkaninfo: Fix win32 fullscreen pnext chain

---

cube/gettime.h

Previously it was returning the time in microseconds.
This also fixes the use of VK_GOOGLE_display_timing which requires a
time in nanoseconds.

Make getTimeInNanoseconds get time in nanoseconds

---

cube/cube.c
cube/cube.cpp

Updated vkcube to properly enable the VK_KHR_portability_subset. Once added, the swizzle formats were then tagged as failing validation and had to be changed to VK_COMPONENT_SWIZZLE_IDENTITY, which does not result in a change in behavior.

vkcube: Updated to support portability extension properly

---

cube/cube.c
cube/cube.cpp

Instead of selecting GPU 0, prefer dGPU, iGPU, vGPU, CPU, OTHER.
In that order.
If user selects specific gpu_number (including 0), use only
that and don't fallback to anything else, even when incorrect.

vkcube: Improve GPU auto-selection

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

When setting device format properties, don't set color attachment-
related bits for DS formats and don't set DS attachment bit for
color formats.
Fixes #445

icd:Consider DS when setting format bits

---

vulkaninfo/vulkaninfo.cpp

Added check for the `VK_EXT_memory_budget` before printing memory usage
and memory budget under VkPhysicalDeviceMemoryProperties.

vulkaninfo: Add check for printing memory budget

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Refactor of vulkaninfo
Manually diffed all 4 outputs and there were no changes to the output (save for memory usage which isn't static even across runs).
Changes include:
* Update License Year
* Simplify QueueFamilyProperties by not querying `VkQueueFamilyProperties2` and making the AppQueueFamilyProperties constructed inside the AppGpu object
* Make printers use the original struct where before they would branch on using the new or old one. (props vs props2 for instance)
* Add helper function to create `VulkanVersion` struct
* Add `optional<T>` type for increased legibility.
* Remove consecutive platform guards
* Initialize variables where appropriate
* Remove unused variables
* Remove unused functions
* Make use of standard algorithms instead of raw for loops.
* Reorder arguments of …

vulkaninfo refactor

---

cube/macOS/cube/AppDelegate.m
cube/macOS/cube/DemoViewController.h
cube/macOS/cube/DemoViewController.m
cube/macOS/cubepp/AppDelegate.mm
cube/macOS/cubepp/DemoViewController.h
cube/macOS/cubepp/DemoViewController.mm

A clean shutdown of the rendering thread (`CVDisplayLink`) whilst the main thread is exiting.
Locally I am working with the Mac version of `RenderDoc` and using samples like the cube projects as part of my local manual testing of the `Vulkan` implementation.
Whilst capturing the cube project with `RenderDoc`. I discovered a crash during shutdown which only happens when `RenderDoc` is attached. I tracked this back to the cube project rendering thread bring active whilst the main thread exit flow is executing ie. static destructors. 
This PR is not critical. I am happy to keep it local to help my testing of the Mac `Vulkan` version of `RenderDoc`.
This PR is one proposed way to fix the shutdown crash when capturing from `RenderDoc` by quitting the demo from the application event …

Trigger demo quit from applicationWillTerminate

---

cube/cube.c
cube/cube.cpp

vkcube computes the model matrix for the cube by repeatedly multiplying
a rotation matrix with it. After a sufficient number of iterations the
matrix becomes disturbed (likely due to numerical errors) and stops
being orthogonal and the cube vertices start scaling along the
XY plane. Over multiple days the cube turns into a rectangular prism.
* Orthonormalize the model matrix after each multiplication to prevent
the scaling.
* Use mat4x4_rotate_Y() instead of mat4x4_rotate() as it is less
verbose.
* Remove unused duplicate vkcube_vs_uniform struct.

vkcube: Fix disturbed rotation after many iterations

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp

Also includes minor fixup of printing of VkSurfaceCapabilitiesKHR, slightly nicer logic in the printing functions, and using an auto-gened function instead of hand coding it.
Fixes #524

vulkaninfo: fix hidden declaration warnings

---

cube/macOS/cube/DemoViewController.m
cube/macOS/cubepp/DemoViewController.mm

Fixed crash on exit for vkcube due to
CVDisplayLinkRelease(displayLink);
Being called twice on shutdown. Removed redundant call that was added recently.

vkcube: fix crash on exit from double delete

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

vkconfig prints arrays as it finds them, even if there is only a "None"
element in it. This commit prevents this element from being printed,
removing confusing results where there is a `count = 1` but contains "None".
fixes https://github.com/LunarG/VulkanTools/issues/1545
Change-Id: I1ef8c63458728a9fd3dc531dc9983f309c851034

vulkaninfo: Dont print None in vkconfig output

---

cube/cube.c

The Vulkan spec states that: "On some platforms, it is normal that maxImageExtent may become (0, 0), for example when the window is minimized. In such a case, it is not possible to create a swapchain due to the Valid Usage requirements."
Yet vkcube previously only handled this path for platforms where currentExtent != 0xFFFFFFFF.

cube: Handle occlusion where currentExtent == 0xFFFFFFFF

---

cube/cube.cpp

Addresses #532 
@jbeich could you please give it a try?

vkcube: Remove unused variable from Wayland build

---

windows-runtime-installer/VulkanRT-License.txt

This is needed to upright the copyright notice for the Vulkan SDK Runtime Installer, as per:
https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/760
I'm not sure whether all the copyrights should be updated,
or just the ones at the top (as the others haven't been modified
since 2016, apparently).  Hopefully reviewers will tell me
whether this is correct.
I also corrected the spelling of "open-source".

windows: updated runtime copyrights to 2017, 2021

---

.github/workflows/build.yml
icd/generated/mock_icd.cpp
icd/generated/mock_icd.h
icd/generated/vk_typemap_helper.h

I missed a couple files in 1.2.185 header update, and the CI check that would have detected it is also missing. This PR fixes both.

Add missing generated files and CI check

---

vulkaninfo/vulkaninfo.cpp

Avoid an amusing and slightly misleading error message:
"The selected gpu (0) is not a valid GPU index. The available GPUs are in the range of 0 to 18446744073709551615."

vulkaninfo: Fix error message when gpus.size()==0

---

scripts/vulkaninfo_generator.py

Vulkaninfo's current autogen breaks on 64 bit flags/bitmasks. While they are not currently necessary for generating the necessary autogen, they may be in the future and it would be wise to update the repo to support them.
The changes include making use of f-strings everywhere. I verified the changes to the codegen as since it generates the same file each time, and they output is identical, there are no breaking changes. Hopefully the use of f-strings make the code-gen more legible.

Vulkaninfo update autogen for 64 bit flags

---

cube/cube.c

Pipeline stage flags should be set before assigned to pWaitDstStageMask
in VkSubmitInfo, otherwise the assigned pointer is invalid.

vkcube: Reorder setting of pipeline stage flags

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

The structure VkPhysicalDeviceShaderIntegerDotProdcutFeaturesKHR contains only a single
feature boolean flag. However, before the final version was published to the public, it
had many boolean flag values. Pre-release drivers often contain support for unpublished
extensions, such as VK_KHR_shader_integer_dot_product. Because the final version was
much smaller than the pre-release version, several drivers try to write to members that
do not exist in the final version, which cause out of bounds writes to the features struct
that vulkaninfo passes into the driver.
By increasing the size of the features struct allocation manually, we can prevent potential
crashes from OOBs writes from drivers.
Fixes #580 
Only discussion item I have is how much documentation of which driver versions caused …

vulkaninfo: Prevent drivers writing out of bounds

---

vulkaninfo/vulkaninfo.cpp

This field has caused numerous crashes and has generally been more trouble than
its worth to have as a default output. Now, a new command line argument is
needed to get vulkaninfo to print tooling info.

vulkaninfo: Make printing ToolProperties optional

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Updated version of https://github.com/KhronosGroup/Vulkan-Tools/pull/425

scripts: initialize properties for VK_EXT_fragment_density_map2 for mock ICD

---

vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h
vulkaninfo/vulkaninfo.md

This PR fixes up the code base so that adding the ability to specify a file to print to is simple. To do this requires:
* Creating a `OutputCategory` enum to hold which type of output `vulkaninfo` should print.
* Refactoring the `user32.dll` code so that it doesn't use any macros and globals are limited to a single pointer to a `User32DllHandle` class (for use in a Win32 callback)
* Creating three functions, `parse_arguments`, `get_printer_create_details`, and `RunPrinter`, that reduce the size of `main()` to a manageable level
* Clean up the logic to decide the destination of the output (stdout or file) and the start string into a very tidy switch statement.

vulkaninfo: Allow specifying file output

---

.github/workflows/build.yml
BUILD.md

Prerequisite for #591 and adding a Wayland build target to cube.

Add dependency on wayland-protocols for cube

---

cmake/FindWaylandProtocols.cmake

- if you cross compile `${PKG_WAYLAND_PROTOCOLS_PREFIX}/share/wayland-protocols` would generate a fixed path pointing to e.g. `/usr/share/wayland-protocols` instead of `path_to_toolchain/usr/share/wayland-protocols` and you'll end up with a missing pkg.

[cube] cmake/FindWaylandProtocols: fix wayland protocol path 

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

The handles allocated for command buffers were not ever freed.

mockicd: Fix FreeCommandBuffers leak

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

vkDestroyDevice would previously clear the queue map which is not correct when there are multiple devices alive.

mockicd: Fix queue destruction for multiple devices

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

The 1.3 update forgot to rename
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES_KHR to
VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES as this
is the non-aliased name. Without it, the fix wouldn't be applied.
Also:
Generate a structure that contains all the structures in the pNext chain as
members rather than relying on malloc to allocate memory for them. This makes the code
much less brittle and easier to extend in the future.

 Fix padding for 1.3 promotion of integer dot product, remove malloc from pNext chains.

---

vulkaninfo/vulkaninfo.h

`VUID-VkImageCreateInfo-usage-00963` says it's invalid to use `VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT` with `VK_IMAGE_USAGE_TRANSFER_SRC_BIT`.
Ran into this on linux.

vulkan tools: Fix image usage error reported by validation layers

---

vulkaninfo/vulkaninfo.h

If this extension is present, it must be enabled when creating a VkDevice.

vulkaninfo: Enable portability subset extension if present

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Expand previous change to include device group creation. Also added some
VK_ENABLE_BETA_EXTENSIONS guards around the portability identifiers.

vulkaninfo: Enable portability extension for device groups

---

cube/cube.c

Make vkcube print a string for device type, which is consistent with
vkcubepp.

Make device selection output constistent

---

BUILD.gn

For reusability in Dawn without depending on entire icd lib, it is helpful to factor out the header into a separate source set so that we don't need to depend on the shared library.

build: Factor out typemap_helper header in rules

---

cube/cube.c
cube/cube.cpp
vulkaninfo/vulkaninfo.h

Make vulkaninfo and vkcube/vkcubepp enable the portability enumeration bit if it is
available.

cube,vulkaninfo: Add portability_enumeration if present

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

They cause unecessary warnings in some compilers and are not necessary for the
code to function. Replaced with if statements.

mock_icd: Remove fallthroughs in switches

---

BUILD.gn

Skia is going to start using these GN files, but does not have chromium's //build. To get them to build, guard those references using `build_with_chromium`. A similar mechanism (with the same argument) is used throughout other third party dependencies.

build: Guard chromium-specific configs in GN

---

.github/workflows/build.yml
cube/cube.cpp

Fix a compiler error with `-DCUBE_WSI_SELECTION=DISPLAY` and Vulkan-Headers v1.3.213
Add more WSI options in addition to the default XCB to the GitHub Actions linux job to catch these types of failures in the future.
Fixes #649

Fix cubepp implicit cast

---

cube/cube.c
cube/cube.cpp

Encountered the crash on a compositor without keyboard, this seems to
fix it.

cube: add null check on wl_*_destroy functions

---

vulkaninfo/vulkaninfo.h

This was recently discovered by new validation messages. The
VkPhysicalDeviceGroupProperties sType member needs to be initialized properly.

vulkaninfo: Set sType in PhysDevGroupProps

---

cube/cube.cpp

Used the wrong extension name by accident.

vkcubepp: Use correct extension for portability enumeration

---

vulkaninfo/vulkaninfo.cpp

When one surface extension fails, today, the whole `vulkaninfo` command fails without providing any information except for the error code. But `vulkaninfo` has still gathered plenty of information to display about other information related to GPU and a great deal of other details.
`vulkaninfo` should ignore failures on an extension, simply display the error, but continue to gather the rest of the info and show it to the user.
Fixes #659

Log Surface Extension Error, But Don't Fail On It

---

cmake/FindVulkan.cmake

I installed a new version of Vulkan SDK and specified the VULKAN_SDK environment variable to the new version and hope the project to use the new version. However, the project always uses the old version of Vulkan SDK in the system default location and ignores the new version that is specified by the VULKAN_SDK environment variable.
The cmake `find_path` and `find_library` commands  search the paths in the following order:
1.  ... ...
2.  ... ...
3. Search the paths specified by the `HINTS` option.
4. ... ...
5. Search cmake variables defined in the Platform files for the current system.
6. Search the paths specified by the `PATHS` option or in the short-hand version of the command
The current code uses `PATHS` to set the search paths of Vulkan SDK by VULKAN_SDK environment variable which …

cmake: Use VULKAN_SDK paths prior to the system paths

---

vulkaninfo/vulkaninfo.h

Avoids setting the color attachment bit for depth stencil formats to prevent crash

Set usage on transient image based on format

---

vulkaninfo/vulkaninfo.h

"Include what you use": `vulkaninfo.h` calls `wl_registry_bind`, thus
ought to include `wayland-client.h`.

vulkaninfo: include wayland-client because its functions are used

---

BUILD.gn

There are several values that in the build file that are only used when
the platform is not Android, but which are declared outside the
`if(!is_android)` block. This causes unused variable errors when
attempting to build chromium on Android with a dependency on this repo.
By moving the definitions into the conditional block the error is
resolved.

Move BUILD.gn values into the scope that uses them

---

icd/CMakeLists.txt

```
[ 91%] Building CXX object icd/CMakeFiles/VkICD_mock_icd.dir/generated/mock_icd.cpp.o
In file included from /home/brad/tmp/Vulkan-Tools/icd/generated/mock_icd.cpp:22:
In file included from /home/brad/tmp/Vulkan-Tools/icd/generated/mock_icd.h:29:
In file included from /usr/local/include/vulkan/vk_icd.h:26:
/usr/local/include/vulkan/vulkan.h:53:10: fatal error: 'xcb/xcb.h' file not found
#include <xcb/xcb.h>
^~~~~~~~~~~
1 error generated.
```

build: Also include XCB header path

---

cube/cube.cpp

cherry pick: be8467a6c64b0ddd31af09619b2dc09d8cfc860b
Currently causes crash for Ubuntu packages

cubepp: Fix presentKHR assert

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Required checking for surface support of a given physical device as well as adding the correct Image usage for transient images.
Fixes #689

vulkaninfo: Fix validation errors

---

cmake/FindVulkanHeaders.cmake

This picks up a few fixes, notably https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1393 which helps with cross-compiling.

cmake: Sync FindVulkanHeaders.cmake with VVL

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Fix #696 
Also:
* Parse & print `VkPhysicalDeviceProperties:driverVersion' according to driver specific formats. Falls back on the Vulkan Major.Minor.Patch if on an unknown platform.
* Switch the `VkPhysicalDeviceProperties:apiVersion` printing to put the major.minor.patch outside of the parenthesis. `apiVersion = 1.3.245 (232343235)` is how it is now printed, instead of ` apiVersion = 232343235 (1.3.245)
* Cleanup the logic around printing UUID arrays. Took some effort but uses the operator<< rather than requiring explicit conversion to strings.

Vulkaninfo: Escape json strings

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

Fix bug where `SHADER_STAGE_ALL_GRAPHICS` and `SHADER_STAGE_ALL` were showing up in the list of set bits for
`VkPhysicalDeviceSubgroupProperties::supportedStages`. When expanding a FlagBits value we should only consider the single-bit options.

vulkaninfo: Fix VkShaderStageFlagBits expansion

---

cube/CMakeLists.txt

When building software for a non-x86 processor on an x86 build machine, or building 32-bit software on a 64-bit build machine, it's still useful to compile demo programs that can be copied into the target environment and run there, even if they won't necessarily be runnable on the build machine.
This also addresses a build failure when cross-compiling and attempting to leave the demos enabled:
CMake Error at cube/CMakeLists.txt:274 (install):
install TARGETS given target "vkcube" which does not exist.
(and similar for the other demos)
Resolves: https://github.com/KhronosGroup/Vulkan-Tools/issues/592

build: Compile vkcube and other demos, even when cross-compiling

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Currently the MockICD only exposed Vulkan 1.1 but in theory supports what ever version the spec is

icd: Set MockICD driver version to header version

---

vulkaninfo/outputprinter.h

When adding a value_description, the json output would incorrectly quote the PrintKeyString output, leading to invalid json being generated.

vulkaninfo: Fix quoting strings in json output

---

cube/cube.c
cube/cube.cpp

Fix the crash when trying to select a negative GPU index and the validation error stating that the apiVersion wasn't set.

Fix negative gpu selection in vkcube & vkcubepp

---

cube/cube.c
cube/cube.cpp

Previously the code assumed that all types were convertable to void*, since they happened to have the same size on 64 bit platforms. But in 32 bit, this is not true.
Now the code converts dispatchable handles to uintptr_t then to void* only for dispatchable types, printing all other types as non-dispatchable 64 bit ints.
@smcv Since there isn't an easy way for me to test these changes, could you verify that this works as intended for you?
Fixes #703

vkcube: Fix object type printing in 32 bit mode

---

vulkaninfo/CMakeLists.txt
vulkaninfo/vulkaninfo.rc.in

The copyright went out of date in 2022 but was never updated. As a precaution for the future, the copyright will now be the current year the file was created in, rather than being hardcoded.

vulkaninfo: Fix rc file copyright and other mistakes

---

icd/generated/mock_icd.cpp
icd/generated/mock_icd.h
scripts/kvt_genvk.py
scripts/mock_icd_generator.py

There are many `vkEnumeratePhysicalDevice*` and `vkGetPhysicalDevice` function that just giving an arbitrary value provides more test coverage when using MockICD with Profiles to test Validation

mockicd: Add more PhysicalDevice functions not in profiles

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

closes https://github.com/KhronosGroup/Vulkan-Profiles/issues/352 (cc @christophe-lunarg)
Some property values in the `vk.xml` are label as `limittype="exact"` and therefor it is not possible at the moment for the Profiles layer to know which value to give. This adds support for all useful property values that would be needed for Validation Layer testing
Note, some properties were removed, but looking back at `git blame` all of them were added for the [same reason to add support for validation layer testing](https://github.com/KhronosGroup/Vulkan-Tools/pull/594) but that was before the Profile Layer system

mockicd: Fix and finish vkGetPhysicalDeviceProperties2KHR

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Expands MockICD to have more Memory Types found on various implementations

mockicd: Add more Memory Types

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

The QUEUE_OPTICAL_FLOW_BIT_NV was getting the 'V' cut off of it, this commit fixes that so that it isn't being removed, as well as making the output more consistent.
Fixes #748

vulkaninfo: Fix wrong stripping in flag strings

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Adds support for
- `vkGetVideoSessionMemoryRequirementsKHR`
- `vkGetPhysicalDeviceVideoFormatPropertiesKHR`
- `vkGetPhysicalDeviceVideoCapabilitiesKHR`
to allow for testing Video test in Validation Layers

mockicd: Add Support for testing Video decoding

---

windows-runtime-installer/VulkanRT-License.txt

This allows the next SDK to build cleanly without generating errors while a more robust solution is devised to automate updating the copyright.

vulkaninfo: Stopgap fix for old copyrights

---

vulkaninfo/vulkaninfo.h

The VK_LUNARG_direct_driver_loading extension, when enabled, causes spurious warnings in the loader. Vulkaninfo should just not enable it to prevent these warnings from apperaing in the output.

vulkaninfo: Dont enable Direct Driver Loading Ext

---

build-android/build_all.sh
cube/android/.gitignore
vulkaninfo/android/.gitignore
vulkaninfo/android/jni/Android.mk
vulkaninfo/android/jni/Application.mk
vulkaninfo/vulkaninfo.h

This change adds a build step to "build-android/build_all.sh" to create a command-line version of `vulkaninfo` for Android devices. Once built, `vulkaninfo` can be pushed to the device and executed using `adb`.
Because it is not possible to create `ANativeWindow` from a native command-line application, `VULKANINFO_WSI_ENABLED` is not defined for Android builds of `vulkaninfo`.

vulkaninfo: Add Android build support

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp

For types like VkSampleCountFlagBits a "VK_" prefix will be added for JSON outputs. This makes the behaviour consistent for JSON output.
Fields that currently use a type of `VkSampleCountFlags` will use a `VK_` prefix in the JSON output of `vulkaninfo`. However, fields that use a type of `VkSampleCountFlagBits` will not have this prefix. For example:
VkSampleCountFlags:
```json
"VkPhysicalDeviceSampleLocationsPropertiesEXT": {
"sampleLocationSampleCounts": [
"VK_SAMPLE_COUNT_1_BIT",
"VK_SAMPLE_COUNT_2_BIT",
"VK_SAMPLE_COUNT_4_BIT"
],
},
```
VkSampleCountFlagBits:
```json
"VkPhysicalDeviceFragmentShadingRatePropertiesKHR": {
"maxFragmentShadingRateRasterizationSamples": "SAMPLE_COUNT_4_BIT",
},
```
The above inconsistent behaviour makes it difficult to post-process JSON output from …

vulkaninfo: Add "VK_" prefix for PrintFlagBits

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Until now, vulkaninfo was only displaying VkFormatFeatureFlagBits, which means that many of the newer capabilities of formats were not being shown. Now, vulkaninfo will default to printing VkFormatFeatureFlagsBits2 and only use VkFormatFeatureFlagBits when the VK_KHR_format_feature_flags_2 is not supported by the device.
While this PR is currently working, I need to perform more testing on the various outputs to verify everything still works as intended.
Fixes #751

vulkaninfo: Use VkFormatFeatureFlags2 by default

---

vulkaninfo/vulkaninfo.cpp

Vulkaninfo does not manually flush the output before exiting, which means that if a crash were to happen during teardown, the stdout buffer may not have finished writing.
To implement this, it was necessary to turn the destructor of Printer into a function, as the lifetime of the printer is longer than the various Vulkan objects that are liable to crash.
This PR comes about to work around issues where some layers/drivers/systems will crash during vkDestroyDevice.

vulkaninfo: Flush before exiting

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Needed for KhronosGroup/Vulkan-ValidationLayers/issues/5616

mock: Add support for DeviceBufferMemoryRequirements

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Needed for KhronosGroup/Vulkan-ValidationLayers/issues/5616

mock: Add support for vkGetDeviceImageMemoryRequirements

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

`GetPhysicalDeviceExternalBufferProperties` changes:
Previous implementation violated property that handle type is at least compatible with itself.
It's needed to implement testing for VUID-VkMemoryAllocateInfo-pNext-00639
`GetFenceWin32HandleKHR/GetFenceFdKHR` changes:
Return not null handles to pass VUID-VkImportFenceWin32HandleInfoKHR-handle-01462
Tested with GHA using this fork: https://github.com/artem-lunarg/Vulkan-ValidationLayers/tree/external-memory2

mock: Extend external memory functionality

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Fix vkGetPhysicalDeviceSparseImageFormatProperties2 and
vkGetPhysicalDeviceSparseImageFormatProperties2KHR queries when
pProperties is null.
Fix vkGetImageSparseMemoryRequirements2 and
vkGetImageSparseMemoryRequirements2KHR queries when
pSparseMemoryRequirements is null.

mock: Fix sparse image 2 gets

---

vulkaninfo/vulkaninfo.h

The tertiary version field is shifted 6 bits to the right, meaning there are only 6 bits left to for the quaternary version field, not 10. See also:
https://github.com/SaschaWillems/vulkan.gpuinfo.org/blob/1e6ca6e3c0763daabd6a101b860ab4354a07f5d3/functions.php#L305
CC @SaschaWillems 
(EDIT: I did not test or run into this problem, just noticed this oddity while trying to understand other version parsing quirks)

vulkaninfo: Reduce NVIDIA quaternary version field to 6 bits

---

vulkaninfo/vulkaninfo.h

Previously, vulkaninfo would enable all instance extensions, which caused validation errors to be generated. Now, vulkaninfo only enables extensions it knows it needs to, such as:
VK_EXT_debug_report
VK_KHR_get_physical_device_properties2
VK_KHR_portability_enumeration
VK_KHR_surface
<platform specific surface extensions>
VK_KHR_get_surface_capabilities2
VK_KHR_surface_protected_capabilities
Fixes #799

vulkaninfo: Only enable necessary instance extensions

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR was blindly writing to the pCounters buffer without first checking that the pCounterCount contained enough space for the data. Now Mock ICD will return VK_INCOMPLETE if not enough space is available as well as write as many elements as there is space for.
Fixes #794

icd: Fix OOB writes in QueuePerfCounters

---

icd/generated/mock_icd.cpp
scripts/mock_icd_generator.py

Adds support for `vkGetDescriptorSetLayoutSupport` so it returns `VK_TRUE`

icd: Add vkGetDescriptorSetLayoutSupport

---

.github/workflows/tools.yml
scripts/known_good.json
tests/icd/mock_icd_tests.cpp

ci: Add tests to github actions runs
Some tests do not need installed drivers, such as MockICD testing, so is
a prime candidate for cloud based CI.
Added the first of many tests for mock ICD that should outline the current capabilities so that current users aren't affected by more invasive modifications.

ci: Add tests to github actions runs for linux and mac

---

icd/CMakeLists.txt
icd/generated/function_definitions.h
icd/mock_icd.h
scripts/mock_icd_generator.py

This PR reintroduces the parameterization changes merged in PR #792 which were accidentally undone in commit ca8bb4ee3cc9afdeca4b49c5ef758bad7cce2c72.
It also fixes a memory leak issue in Mock ICD which can be observed if command pools are not destroyed before device destruction, as the `command_pool_buffer_map` will hold on to placeholder command buffer dispatchable handle allocations that would never get freed.

Redo parameterization changes of Mock ICD for Vulkan SC and other improvements

---

icd/CMakeLists.txt

Added so that future maintainers know why these variables exist.

icd: Document parametization for VulkanSC

---

CMakeLists.txt
cube/CMakeLists.txt
vulkaninfo/CMakeLists.txt

CMake 3.15 introduced CMAKE_MSVC_RUNTIME_LIBRARY as a way to control the CRT linked to by default. The old way of searching and replacing CMAKE_<LANG>_FLAGS does not work because CMake no longer adds the /MD flag in newer versions. Thus we can remove that code and replace it with a single instance of CMAKE_MSVC_RUNTIME_LIBRARY.

build: Default to using the static CRT for MSVC

---

icd/generated/function_definitions.h
scripts/mock_icd_generator.py

Adds support for the `vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR` needed so MockICD can run with profiles for  upcoming `VK_KHR_cooperative_matrix` VVL tests

icd: Add VK_KHR_cooperative_matrix support

---

CMakeLists.txt
scripts/CMakeLists.txt

This is analogous to the same variable type used in VVL to indicate target API variant and is used to specify the `--api` argument of `update_deps.py`.
To be clear, previously, `update_deps.py` was not automatically invoked in the tools build system, hence the new use of the `API_TYPE` cmake variable.

build: Add API_TYPE variable

---

vulkaninfo/vulkaninfo.h

This extension may be required to be enabled to enumerate HDR formats, best to enable it if its available.

vulkaninfo: Enable Swapchain Colorspace ext

---

vulkaninfo/vulkaninfo.cpp

The help text indicates that -j=<GPU> should work, but was never implemented when the code was refactored.
Partially solves #840

vulkaninfo: Make -j=<GPU> work

---

cube/cube.c
cube/cube.cpp

Additionally add support for RGB565 and RGBA5551 pixel formats, because some Vulkan drivers under QNX report these formats first as preferable.
And add #include <errno.h> because the source is using errno, but under QNX there is no indirect inclusion of this header by other headers. So we need explicitly include errno.h to get errno declared.

Add QNX support (VK_QNX_screen_surface) to C and C++ variants of vkcube.

---

icd/generated/function_definitions.h
scripts/mock_icd_generator.py

Add support for `VkSurfacePresentModeCompatibilityEXT` which allows Validation Layers to test with `VK_EXT_surface_maintenance1` in CI

icd: Add VkSurfacePresentModeCompatibilityEXT support

---

icd/generated/function_definitions.h
scripts/mock_icd_generator.py

Most tests will need `VK_SCOPE_SUBGROUP_KHR` support

icd: Add second VkCooperativeMatrixPropertiesKHR field

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

The struct VkSurfacePresentModeCompatibilityEXT and VkSurfacePresentScalingCapabilitiesEXT can only be included in the VkSurfaceCapabilities2KHR pNext chain if a VkSurfacePresentModeEXT struct is in the pNext chain for VkPhysicalDeviceSurfaceInfo2KHR. In other words, the autogen for this extension is not adequate and needs to be special cased.
This is doubly true because the aformentioned structs are 'per-present-mode' so the output needs to handle printing each struct once per present mode available, which is not possible with autogenerated code currently.
The easiest solution is to just remove the surface_maintenance1 structs from autogen in the pNext chain (but keep the autogenerated printing functions). Then setup the pNext chains appropriate and make the necessary calls, before …

vulkaninfo: Support VK_EXT_surface_maintenance1 properly

---

.github/workflows/tools.yml
CMakeLists.txt
cube/CMakeLists.txt
cube/macOS/cube/cube.cmake
cube/macOS/cubepp/cubepp.cmake
scripts/known_good.json
tests/CMakeLists.txt
vulkaninfo/CMakeLists.txt

The Vulkan-Loader now supports find_package properly, allowing this repo to drop
the ad-hoc creation of the Vulkan::Vulkan target.
This allows enabling of tests on windows CI.

build: Fix Windows build when tests are enabled

---

cube/CMakeLists.txt

The build step to compile shaders put them in the build directory rather than the source directory.

cube: Fix shader compilation destination

---

CMakeLists.txt
icd/CMakeLists.txt
icd/generated/function_declarations.h
icd/generated/function_definitions.h
scripts/mock_icd_generator.py
tests/CMakeLists.txt
tests/icd/mock_icd_tests.cpp

This commit adds support for the VkPhysicalDeviceDriverProperties struct in the output of vkGetPhysicalDeviceProperties2. This is useful for users of Mock ICD wishing to know the version of MockICD used. The driverInfo field is used for this purpose and contains the git branch & tag info data. The use of Git in CMake is how the information is seamlessly gotten and provided to the source code in the form of compile definitions.
Fixes #788

icd: Add VkPhysicalDeviceDriverProperties

---

CMakeLists.txt
cube/CMakeLists.txt
icd/CMakeLists.txt
vulkaninfo/CMakeLists.txt

- APPEND CMAKE_MODULE_PATH
- Remove overly specific CMake code
- Use CMAKE_SYSTEM_NAME to detect Linux/BSD
- Remove unused code
- Simplify install target code
- Use PRIVATE instead of PUBLIC
- Prefer target based commands

cmake: General cleanup

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp

Previously, the code generator assumed enums were always printed as key-value pairs, and not in an array. This led to using object syntax inside of arrays in the JSON output, which is invalid, and is now fixed.

vulkaninfo: Fix printing arrays of Enums

---

CMakeLists.txt
cube/android/jni/Application.mk
cube/cube.cpp

Addresses various other issues with setting compiler flags.
CMAKE_C_FLAGS / CMAKE_CXX_FLAGS should NOT be used anymore.
Addressed one minor C++17 issue caused by [[nodiscard]].
Remove compiler flags from Application.mk since they weren't needed and will soon be entirely replaced by CMake.
closes #711

cmake: Upgrade to C++17

---

vulkaninfo/CMakeLists.txt

Not needed
FYI @mikes-lunarg who removed this in this commit: https://github.com/KhronosGroup/Vulkan-Tools/pull/723

vulkaninfo: Remove install for appbundle

---

BUILD.md

- This repo doesn't use presets
- Don't show invalid usage of rm. It works on Linux but not Mac.
- Use VulkanHeaders as an example instead of glslang

docs: Fix invalid/confusing documentation

---

CMakeLists.txt
vulkaninfo/CMakeLists.txt

- Fix problematic usage of CMAKE_SOURCE_DIR
- Removed unused folder code
- Take advantage of modern CMake functionality
- Use target_sources
- Cleanup VULKANINFO_BUILD_DLL_VERSIONINFO code
- Minor iOS fix

cmake: Cleanup VulkanInfo

---

icd/generated/function_definitions.h
scripts/mock_icd_generator.py

Allows MockICD test to return a non-negative `fd` for `vkGetMemoryFdKHR`

icd: Add vkGetMemoryFdKHR support

---

icd/generated/function_definitions.h
scripts/mock_icd_generator.py

add `vkGetMemoryHostPointerPropertiesEXT` to return a valid memory type for `VK_EXT_external_memory_host` tests

icd: Add vkGetMemoryHostPointerPropertiesEXT support

---

vulkaninfo/vulkaninfo.cpp

Was VK_EXT_surface_maintance_1 which is wrong.
Fixes #908

vulkaninfo: Fix typo in VK_EXT_surface_maintance1

---

CMakeLists.txt
cube/cube.cpp
cube/macOS/cube/CMakeLists.txt
cube/macOS/cubepp/CMakeLists.txt
scripts/known_good.json

Otherwise layers won't work on Apple

cube: Fix layers on Apple

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

If a structure is promoted to a core version, and the version used is equal or greater than that, the structure should not be included, since it will be a part of the core structure

vulkaninfo: Fix including promoted structures

---

scripts/gn/generate_vulkan_icd_json.py

generate_vulkan_icd_json.py:31: SyntaxWarning: invalid escape sequence'\ '
"""Like regular glob but replaces \ with / in returned paths."""

[scripts] [gn] Fix Python 3.12 compatibility

---

scripts/vulkaninfo_generator.py
vulkaninfo/CMakeLists.txt
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

This change introduces the possibility to parameterize vulkaninfo builds based on API variant.
It is similar to changes applied to MockICD and other Vulkan ecosystem repositories in order to enable downstream Vulkan SC support.

vulkaninfo: API parameterization changes

---

cube/cube.c

Volk makes the manual loading of function pointers unnecessary.

cube: Remove debug utils function loading

---

icd/generated/function_definitions.h
icd/mock_icd.h
scripts/mock_icd_generator.py
tests/icd/mock_icd_tests.cpp

This change adds the necessary functionalities to the MockICD in order to be able to run all video decode/encode validation tests with MockICD and thus on github CI actions.

icd: Add video support

---

.github/workflows/tools.yml
cube/CMakeLists.txt

Now the loader is installed in the app so it is self-contained.
Just requires fixing up the RPATH.
closes #921

Fix MacOS installation of vkcube

---

cube/cube.cpp

Avoids relying on Vulkan-Hpp for fixing vkcubepp regression

Fix vkcubepp installation on MacOS

---

vulkaninfo/vulkaninfo.h

libvulkan.dylib.1 doesn't exist

Check for libvulkan.1.dylib

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
windows-runtime-installer/VulkanRT-License.txt

This fixes the last warnings when using the profile. I did not find a better way than to use an exceptions list, but this should be fine as I don't think there will be another case for this.

vulkaninfo: Fix promoted structure exceptions

---

icd/VkICD_mock_icd.json.in
icd/generated/function_declarations.h
icd/generated/function_definitions.h
scripts/known_good.json
scripts/kvt_genvk.py
windows-runtime-installer/VulkanRT-License.txt

build: Update to header 1.3.275

---

cube/CMakeLists.txt
windows-runtime-installer/VulkanRT-License.txt

On Ubuntu 20.04, it was found that the validation layers fail to launch in vkcube & vkcubepp
due to a missing dependency on libpthread. While newer Ubuntu versions use a glibc version
where libpthread is integrated into libc, older ubuntu's do not so we need to link threads
directly in order for validation layers to be loadable.

cube: Link to Threads directly 

---

cube/macOS/cube/CMakeLists.txt
cube/macOS/cubepp/CMakeLists.txt
scripts/known_good.json

The latest MoltenVK known good has changed where the build artifacts are located. This change to the cmake files takes that into account.

Lunarg ios fixes

---

vulkaninfo/vulkaninfo.cpp

This information from VkSurfaceCapabilitiesKHR is explicitly called out in the VK_EXT_surface_maintenance1 extension specification as something which will change based on the present mode used. It would be helpful for vulkaninfo to report it as such.

vulkaninfo: Add minImageCount/maxImageCount to VK_EXT_surface_maintenance1

---

icd/generated/function_definitions.h
scripts/mock_icd_generator.py

This is needed so we can test and catch regressions for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6310
I really don't like this PR, but the amount of time it will take to get a proper "fault injection layer" or "Set the return value for MockICD for each function" is higher then what the ROI is currently.
I will be MORE than happy to remove this code in the future for anything better, but for now it serves a purpose and improves validation layer testing coverage

icd: Add special fault injection logic

---

icd/generated/function_definitions.h
scripts/mock_icd_generator.py

Updates external memory properties to be able to write tests for: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7790
Tested with VVL here: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commits/artem-test-mock/

icd: Add external memory properties

---

cube/cube.c

When swapchain is recreated the entire surface should be redrawn

cube: Fix incremental present on swapchain recreate

---

cube/CMakeLists.txt
cube/cube.c
cube/cube.cpp
cube/macOS/cube/DemoViewController.m
cube/macOS/cubepp/DemoViewController.mm

See also:
Cannot build DEMOS.sln
https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/1417
Volk requires that VK_NO_PROTOTYPES be defined before vulkan.h or vulkan.hpp is included.  Currently, the various flavors of vkcube hide this definition in the cube/CMakeLists.txt file, which can confuse users who may copy the source for their own use, and may require investigation to figure out why it doesn't "just work".
This change makes the #define explicit in the cube.c and cube.cpp source files, which should both be clearer and be more similar to how most applications use Volk.

cube: Make Volk requirement explicit

---

vulkaninfo/vulkaninfo.cpp

was broken by 3a2b64a26f74734baf83f61ef62800321a2961e5, better disable it until it gets broken again

vulkaninfo: disable _set_abort_behavior for MinGW

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/outputprinter.h
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

There are now multiple structs in pNext chains which require calling once to get the size, allocating memory, then calling again to get the data. The codegen now handles such functions, although not very cleanly.

vulkaninfo: Support 2-call structs in codegen for pNext chains

---

.github/workflows/tools.yml
cube/cube.c

ALooper_pollAll is removed in NDK r27, switch to using ALooper_pollOnce instead. Since it was already being called in a loop, all we have to do is change the function name.
Fixes #1015

cube: Change ALooper_pollOnce to ALooper_pollAll

---

cube/cube.c

wl_display_dispatch() may not process all events.

cube: roundtrip to ensure all globals are processed

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

This option restores behavior which will query all structs regardless of whether they were promoted or replaced by another struct. For example, VkPhysicalDeviceVulkan12Features contains all of the features that VkPhysicalDeviceVulkanMemoryModelFeatures does, so only the former needs to be output. However, some users will want both structs present regardless and the --show-all-structs option allows that behavior.
This commit also removes redundant checks when iterating the pNext chains while printing, as those same checks occur when the chain is being created, removing duplicate code-gen and runtime checks.

vulkaninfo: Add --show-promoted-structs option

---

scripts/vulkaninfo_generator.py
vulkaninfo/generated/vulkaninfo.hpp
vulkaninfo/vulkaninfo.h

VulkanSC found that the twocall machinery makes the assumption that there is at least one property output struct with array members. While this breaks VulkanSC (results in unresolved external symbol), it also breaks Vulkan when used with older `vk.xml` files where this assumption may also not hold true. Also, instead of unconditionally querying properties twice, only call the query again if the given output struct has array members.
_Note: the current refinement is still "happens to work" territory, as a generic solution would need to do `n` calls to query, depending on the number of nesting of structs with array members. `twocall` works today but may break tomorrow._

Fix twocall_chain_vectors mechanism

---

vulkaninfo/vulkaninfo.cpp
vulkaninfo/vulkaninfo.h

Plus other small improvements.

vulkaninfo: Correctly query per-surface queue support

---

cube/cube.c

The --validate-checks-disabled flag was unused, so will be removed.

vkcube: Remove unused command line option

---

.github/workflows/tools.yml
cube/CMakeLists.txt
cube/android/CMakeLists.txt
cube/cube.c
cube/cube.cpp
cube/macOS/cube/CMakeLists.txt
cube/macOS/cubepp/CMakeLists.txt
cube/wayland_loader.h
cube/xcb_loader.h
cube/xlib_loader.h

By changing the selection of a WSI platform from a build time choice to a runtime choice, this allows the removal of vkcube-wayland as a separate binary.
Use `--wsi <xlib|xcb|wayland|display|directfb>` to choose the WSI platform that vkcube will render with. The chosen platform must be one that vkcube was compiled with support for, so directfb will be unavailable without changing the build parameters to enable it.
These changes have been made to both vkcube and vkcubepp.
Platforms which do not have multiple WSI platforms, such as windows, android, and apple (metal is the only non-deprecated platform) do not have this option as there aren't any platforms to choose from.

cube: Support runtime selection of WSI platform

---

vulkaninfo/vulkaninfo.h

If the visual passed to XCreateWindow is not the default one, it can cause a BadMatch error. Usually the first one returned does work, but in certain cases we need to search through all the visuals to find one that matches the default visual. This was seen on an xrdp session on Rocky 9.
Fixes #1042

vulkaninfo: On X11 use default visual

---

scripts/update_deps.py

This PR propagates [these](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8705) changes from the VVL.

Update deps enahancements

---

.github/workflows/tools.yml

This creates dependency for things to run Github Actions to better prevent wasted CI on things

ci: Build dependency for Github Actions

---

vulkaninfo/vulkaninfo.h

This change makes calls using GetVectorInit() to start with an already created buffer of size 64, allowing for the Vulkan implementation to immediately fill in the buffer, rather than having to call the enumerate function twice. This change is primarily motivated to reduce the spam VK_LOADER_DEBUG=all produces when run with vulkaninfo.

vulkaninfo: Call enumerate functions with scratch buffer

---

cube/macOS/cube/CMakeLists.txt
cube/macOS/cubepp/CMakeLists.txt

This was accidentally undone during the changes to cube to handle runtime WSI selection. By not linking, vkcube does not work unless the SDK is installed globally (ie, moltenvk is available globally).

cube: Link to Vulkan-Loader on macOS

---

cube/cube.c
cube/cube.cpp

Add condition to filter if the GPU support the surface.
Solve https://github.com/KhronosGroup/Vulkan-Tools/issues/950

vkcube and vkcubepp: Check if GPU support the surface

---

vulkaninfo/vulkaninfo.h

vulkaninfo: Fix initializing vectors of structs

---

icd/generated/function_declarations.h
icd/generated/function_definitions.h
scripts/generate_source.py
scripts/kvt_genvk.py
scripts/mock_icd_generator.py

closes https://github.com/KhronosGroup/Vulkan-Tools/issues/1072

icd: Add VkPhysicalDeviceMaintenance3Properties

---

cube/cube.cpp

1. std::tolower() returns an `int` value. Implicit converting an `int` to a `char` may trigger compiler warnings (-Wconversion on gcc and clang).
This change adds an explicit cast to suppress the implicit conversion warnings.
2. Previously we used `assert(!"....")` to show error messages. This does an implicit conversion from `const char*` to `bool` which triggers compiler warnings (-Wconversion).
This change replaces it with `assert(false && "...")` which doesn't trigger the warning.
Bug: https://fxbug.dev/378964821

vkcubepp: Fix implicit cast compiler warnings

---

cube/BUILD.gn
cube/cube.cpp
cube/fuchsia/flatland_view.cpp
cube/fuchsia/flatland_view.h
cube/fuchsia/meta/vkcube-on-fb.cml
cube/fuchsia/meta/vkcube-on-scenic.cml

This change was originally in Fuchsia's Vulkan-Tools fork (https://fxrev.dev/441056). It adds Fuchsia OS
(https://fuchsia.dev) support to vkcubepp.
Fuchsia has two WSI platforms available: It can render directly to display frame buffer (`fuchsia_display`), or use Fuchsia's Scenic compositor (`fuchsia_scenic`).
All Fuchsia-specific code is under VK_USE_PLATFORM_FUCHSIA ifdef build guards and is only compiled for Fuchsia targets.
This change also adds a BUILD.gn file used for Fuchsia in-tree builds.
Test: vkcube-on-fb and vkcube-on-scenic on Fuchsia
Bug: https://fxbug.dev/378964821

vkcubepp: Support Fuchsia

---

scripts/known_good.json

Remove the reference to the vulkan-tmp-1.4.309 branch which will be deleted eventually. This vulkan-sdk-1.4.309 is branched at the same location as the tmp branch.

build: update volk branch to vulkan-sdk-1.4.309

---

vulkaninfo/vulkaninfo.cpp

The "Video Profiles" element must be a JSON Object in order for the sub elements to have names. The outputprinter helper doesn't prevent mixing objects inside of arrays, so this wasn't caught during development.

vulkaninfo: Use Object for "Vulkan Profiles" array

---

cube/cube.cpp

The chains were including the structs even when protected memory isn't desired, triggering validation errors.

cube: Fix protected memory pNext chains

---

cube/cube.c
cube/cube.cpp

If platform is WSI Display, vkcube will use physical device when creating surface.

vkcube & vkcubepp: Select physical device before create surface if platform is WSI Display

---

cube/cube.c
cube/cube.cpp

Modifies cube & cubepp to re-record the command buffers each frame instead of pre-recording them at application startup and during resize.
This enables vast refactoring to use best practices for organizing frame and swapchain data into two resource groups: per-submission, and per- swapchain-image. A submission resource is any data needed to render (uniform buffer, descriptor set), any command buffers, the image acquire semaphore, and the fence used in the submission. There are currently two submission resource sets, and the application alternates between the two on subsequent frames. The swapchain-image resources are separate because they are dependent on the number of swapchain images and because the swapchain image index used each frame isn't deterministic.
In addition to the above …

cube: Re-record command buffers each frame

---

cube/cube.c
cube/cube.cpp

Better indicates the error that triggered the message,
and what the user should do about it.
Also update the formatting of the cube source files to use clang-format-18 since they hadn't been updated in a while.

cube: Update missing WSI extension messages 

---

cube/CMakeLists.txt

Previously volk was doing this for cube, but with that removed vkcube/vkcubepp have to link it themselves.

cube: Link to CMAKE_DL_LIBS

---

cube/cube_functions.h

Ensure `vkCreateDisplayPlaneSurfaceKHR` is loaded using `vkGetInstanceProcAddr` rather than `vkGetDeviceProcAddr`.

cube: Fix validation warning

---

cube/cube.c
cube/cube.cpp

In Wayland sessions, X11 is still available through a compatibility layer, but should effectively never be used over a native Wayland connection if the application is capable of that.

cube: prefer Wayland over X11 when available

---

cube/CMakeLists.txt
cube/wayland_loader.h
cube/xcb_loader.h
cube/xlib_loader.h

The library names of Xcb, Xlib, and Wayland do not need to be queried from pkg-config, instead they can be hardcoded to use the fallback names.
The intent of querying the library names was to prevent issues where the hardcoded name was not the platform-appropriate name. But because <library>_LINK_LIBRARIES can have more than one library name, the logic to assign <library>_LINK_LIBRARIES into a compile definition breaks horribly. While it is possible to handle this in CMake, the dlopen code would also have to handle it which is much more error prone.

build: Remove pkg-config provided library names

---

cube/cube.c

This sets the `WM_NAME` property in X11/Xwayland, usually displayed as the name on the application titlebar.
The motivation for this is to help with automated testing environments on Xwayland. Testing frameworks such as wltest may use compositor methods to automate controlling a window to perform tests. When running through Xwayland, clients normally do not have much information exposed about them which can make it difficult for the test framework to find and manipulate the correct window.
This change defines the `WM_NAME` property to allow scripting frameworks (such as Kwin's js API) to be able to find Vkcube on Xwayland.

vkcube: use _NET_WM_NAME property on X11

---

vulkaninfo/vulkaninfo.cpp

Allows the use of `--show-promoted-structs` in Profile JSON output, allowing "all" structs to be printed. Useful because it prevents the user having to determine which version of a struct to use.

vulkaninfo: Support promoted structs in Profile JSON output
